// EV Best Price Finder — Data File
// Updated: March 2026
// Update this file monthly with latest pricing from Carvana, CarMax, AutoTrader, etc.

export interface EvDeal {
  id: string;
  brand: string;
  model: string;
  year: number;
  bodyType: "sedan" | "suv" | "truck" | "hatchback" | "van";
  msrp: number;
  bestNewPrice: number | null;
  bestNewPlatform: string | null;
  bestNewUrl: string;
  bestUsedPrice: number | null;
  bestUsedPlatform: string | null;
  bestUsedUrl: string;
  bestUsedYear: number | null;
  bestUsedMileage: string | null;
  range: number;
  zeroToSixty: string;
  chargingSpeed: string; // miles added per 15 min fast charge
  trueValueScore: number;
  efficiency: number; // mi/kWh
  cargoSpace: string;
  warranty: string;
  fuelSavings: { monthly: number; annual: number; fiveYear: number };
  ownershipCost: {
    electricity5yr: number;
    insurance5yr: number;
    maintenance5yr: number;
    totalCost5yr: number;
    resalePercent: number;
    resaleValue: number;
    netCost: number;
  };
  batteryDetails: {
    capacity: string;
    realWorldRange: string;
    coldWeatherRange: string;
    degradationNote: string;
  };
  platforms: { name: string; url: string }[];
  trendPercent: number; // negative = price drop (good for buyers)
  trendNote: string;
  featured?: boolean;
  featuredNote?: string;
  discontinued?: boolean;
}

export const EV_DEALS: EvDeal[] = [
  // === SEDANS ===
  {
    id: "tesla-model-3-2024",
    brand: "Tesla",
    model: "Model 3",
    year: 2024,
    bodyType: "sedan",
    msrp: 38990,
    bestNewPrice: 36500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/tesla/model-3",
    bestUsedPrice: 29800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/tesla-model-3",
    bestUsedYear: 2023,
    bestUsedMileage: "18k mi",
    range: 272,
    zeroToSixty: "5.8s",
    chargingSpeed: "170 mi",
    trueValueScore: 82,
    efficiency: 3.8,
    cargoSpace: "23 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 92, annual: 1104, fiveYear: 5520 },
    ownershipCost: {
      electricity5yr: 2526,
      insurance5yr: 9000,
      maintenance5yr: 4500,
      totalCost5yr: 52526,
      resalePercent: 52,
      resaleValue: 18980,
      netCost: 33546,
    },
    batteryDetails: {
      capacity: "60 kWh",
      realWorldRange: "245-265 mi",
      coldWeatherRange: "190-210 mi",
      degradationNote: "~5% loss at 50k mi; Tesla batteries hold up well",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/tesla/model-3" },
      { name: "Carvana", url: "https://www.carvana.com/cars/tesla-model-3" },
      { name: "CarMax", url: "https://www.carmax.com/cars/tesla/model-3" },
      { name: "Tesla.com", url: "https://www.tesla.com/model3" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/tesla-model_3/" },
    ],
    trendPercent: -3.8,
    trendNote: "Used prices softening significantly",
  },
  {
    id: "tesla-model-s-2024",
    brand: "Tesla",
    model: "Model S",
    year: 2024,
    bodyType: "sedan",
    msrp: 74990,
    bestNewPrice: 71000,
    bestNewPlatform: "Tesla.com",
    bestNewUrl: "https://www.tesla.com/models",
    bestUsedPrice: 58500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/tesla/model-s",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 405,
    zeroToSixty: "3.1s",
    chargingSpeed: "200 mi",
    trueValueScore: 68,
    efficiency: 3.2,
    cargoSpace: "28 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/150k battery",
    fuelSavings: { monthly: 87, annual: 1044, fiveYear: 5220 },
    ownershipCost: {
      electricity5yr: 3000,
      insurance5yr: 12000,
      maintenance5yr: 4500,
      totalCost5yr: 90500,
      resalePercent: 48,
      resaleValue: 34080,
      netCost: 56420,
    },
    batteryDetails: {
      capacity: "100 kWh",
      realWorldRange: "370-395 mi",
      coldWeatherRange: "290-320 mi",
      degradationNote: "~4% loss at 50k mi; flagship battery quality",
    },
    platforms: [
      { name: "Tesla.com", url: "https://www.tesla.com/models" },
      { name: "CarMax", url: "https://www.carmax.com/cars/tesla/model-s" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/tesla/model-s" },
      { name: "Carvana", url: "https://www.carvana.com/cars/tesla-model-s" },
    ],
    trendPercent: -4.0,
    trendNote: "Luxury sedan market softening",
  },
  {
    id: "bmw-i4-2024",
    brand: "BMW",
    model: "i4 eDrive40",
    year: 2024,
    bodyType: "sedan",
    msrp: 52200,
    bestNewPrice: 46800,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/bmw/i4",
    bestUsedPrice: 38900,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/bmw-i4",
    bestUsedYear: 2023,
    bestUsedMileage: "12k mi",
    range: 301,
    zeroToSixty: "5.5s",
    chargingSpeed: "108 mi",
    trueValueScore: 78,
    efficiency: 3.5,
    cargoSpace: "18 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 89, annual: 1068, fiveYear: 5340 },
    ownershipCost: {
      electricity5yr: 2743,
      insurance5yr: 10500,
      maintenance5yr: 5000,
      totalCost5yr: 65043,
      resalePercent: 45,
      resaleValue: 21060,
      netCost: 43983,
    },
    batteryDetails: {
      capacity: "83.9 kWh",
      realWorldRange: "270-290 mi",
      coldWeatherRange: "210-240 mi",
      degradationNote: "~6% at 50k mi; solid BMW battery management",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/bmw/i4" },
      { name: "Carvana", url: "https://www.carvana.com/cars/bmw-i4" },
      { name: "CarMax", url: "https://www.carmax.com/cars/bmw/i4" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/bmw-i4_gran_coupe/" },
    ],
    trendPercent: -5.2,
    trendNote: "Dealers offering strong incentives",
  },
  {
    id: "polestar-2-2024",
    brand: "Polestar",
    model: "Polestar 2",
    year: 2024,
    bodyType: "sedan",
    msrp: 44900,
    bestNewPrice: 38500,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/polestar-2/",
    bestUsedPrice: 29200,
    bestUsedPlatform: "CarGurus",
    bestUsedUrl: "https://www.cargurus.com/Cars/l-Used-Polestar-2-d3036",
    bestUsedYear: 2023,
    bestUsedMileage: "20k mi",
    range: 270,
    zeroToSixty: "6.2s",
    chargingSpeed: "100 mi",
    trueValueScore: 80,
    efficiency: 3.4,
    cargoSpace: "14 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 90, annual: 1080, fiveYear: 5400 },
    ownershipCost: {
      electricity5yr: 2824,
      insurance5yr: 8500,
      maintenance5yr: 4500,
      totalCost5yr: 54324,
      resalePercent: 42,
      resaleValue: 16170,
      netCost: 38154,
    },
    batteryDetails: {
      capacity: "78 kWh",
      realWorldRange: "240-260 mi",
      coldWeatherRange: "185-210 mi",
      degradationNote: "~6% at 50k mi; Volvo/Geely battery tech",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/polestar-2/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Polestar-2-d3036" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/polestar/polestar-2" },
    ],
    trendPercent: -6.0,
    trendNote: "Steep depreciation creates great used deals",
  },
  {
    id: "lucid-air-pure-2024",
    brand: "Lucid",
    model: "Air Pure",
    year: 2024,
    bodyType: "sedan",
    msrp: 69900,
    bestNewPrice: 63000,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/lucid/air",
    bestUsedPrice: 49500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/lucid/air",
    bestUsedYear: 2023,
    bestUsedMileage: "10k mi",
    range: 410,
    zeroToSixty: "3.8s",
    chargingSpeed: "200 mi",
    trueValueScore: 72,
    efficiency: 4.6,
    cargoSpace: "32 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 95, annual: 1140, fiveYear: 5700 },
    ownershipCost: {
      electricity5yr: 2087,
      insurance5yr: 11000,
      maintenance5yr: 4500,
      totalCost5yr: 81587,
      resalePercent: 40,
      resaleValue: 25200,
      netCost: 56387,
    },
    batteryDetails: {
      capacity: "92 kWh",
      realWorldRange: "380-400 mi",
      coldWeatherRange: "290-330 mi",
      degradationNote: "~5% at 50k mi; Lucid's industry-leading efficiency",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/lucid/air" },
      { name: "CarMax", url: "https://www.carmax.com/cars/lucid/air" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/lucid-air/" },
    ],
    trendPercent: -7.5,
    trendNote: "Best luxury EV value on the used market",
  },
  {
    id: "nissan-leaf-2024",
    brand: "Nissan",
    model: "Leaf S",
    year: 2024,
    bodyType: "sedan",
    msrp: 28140,
    bestNewPrice: 24500,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/nissan-leaf/",
    bestUsedPrice: 17800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/nissan-leaf",
    bestUsedYear: 2023,
    bestUsedMileage: "22k mi",
    range: 149,
    zeroToSixty: "7.4s",
    chargingSpeed: "50 mi",
    trueValueScore: 75,
    efficiency: 3.3,
    cargoSpace: "24 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 91, annual: 1092, fiveYear: 5460 },
    ownershipCost: {
      electricity5yr: 2909,
      insurance5yr: 7000,
      maintenance5yr: 4000,
      totalCost5yr: 38409,
      resalePercent: 35,
      resaleValue: 8575,
      netCost: 29834,
    },
    batteryDetails: {
      capacity: "40 kWh",
      realWorldRange: "125-140 mi",
      coldWeatherRange: "100-115 mi",
      degradationNote: "~8% at 50k mi; air-cooled battery degrades faster than liquid-cooled",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/nissan-leaf/" },
      { name: "Carvana", url: "https://www.carvana.com/cars/nissan-leaf" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Nissan-LEAF-d2077" },
    ],
    trendPercent: -5.0,
    trendNote: "Cheapest EV entry point on the market",
  },

  // === SUVs ===
  {
    id: "tesla-model-y-2024",
    brand: "Tesla",
    model: "Model Y",
    year: 2024,
    bodyType: "suv",
    msrp: 44990,
    bestNewPrice: 42000,
    bestNewPlatform: "Tesla.com",
    bestNewUrl: "https://www.tesla.com/modely",
    bestUsedPrice: 33500,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/tesla-model-y",
    bestUsedYear: 2023,
    bestUsedMileage: "20k mi",
    range: 310,
    zeroToSixty: "5.0s",
    chargingSpeed: "162 mi",
    trueValueScore: 85,
    efficiency: 3.5,
    cargoSpace: "68 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 95, annual: 1140, fiveYear: 5700 },
    ownershipCost: {
      electricity5yr: 2743,
      insurance5yr: 9500,
      maintenance5yr: 4500,
      totalCost5yr: 58743,
      resalePercent: 55,
      resaleValue: 23100,
      netCost: 35643,
    },
    batteryDetails: {
      capacity: "75 kWh",
      realWorldRange: "280-300 mi",
      coldWeatherRange: "215-245 mi",
      degradationNote: "~5% at 50k mi; best-selling EV for a reason",
    },
    platforms: [
      { name: "Tesla.com", url: "https://www.tesla.com/modely" },
      { name: "Carvana", url: "https://www.carvana.com/cars/tesla-model-y" },
      { name: "CarMax", url: "https://www.carmax.com/cars/tesla/model-y" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/tesla/model-y" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/tesla-model_y/" },
    ],
    trendPercent: -4.2,
    trendNote: "Prices dropping — great time to buy",
  },
  {
    id: "chevy-equinox-ev-2024",
    brand: "Chevrolet",
    model: "Equinox EV LT",
    year: 2024,
    bodyType: "suv",
    msrp: 33900,
    bestNewPrice: 29200,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/chevrolet/equinox-ev",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 319,
    zeroToSixty: "6.0s",
    chargingSpeed: "150 mi",
    trueValueScore: 94,
    efficiency: 3.6,
    cargoSpace: "57 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 96, annual: 1152, fiveYear: 5760 },
    ownershipCost: {
      electricity5yr: 2667,
      insurance5yr: 8000,
      maintenance5yr: 4500,
      totalCost5yr: 44367,
      resalePercent: 50,
      resaleValue: 14600,
      netCost: 29767,
    },
    batteryDetails: {
      capacity: "85 kWh",
      realWorldRange: "290-310 mi",
      coldWeatherRange: "220-250 mi",
      degradationNote: "Too new for real-world data; Ultium platform promising",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/chevrolet/equinox-ev" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/chevrolet-equinox_ev/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Chevrolet-Equinox-EV-d3267" },
    ],
    trendPercent: -6.1,
    trendNote: "Aggressive dealer discounts",
    featured: true,
    featuredNote: "Most affordable long-range EV on the market. $29k for 319 miles of range is unmatched.",
  },
  {
    id: "ford-mach-e-2024",
    brand: "Ford",
    model: "Mustang Mach-E",
    year: 2024,
    bodyType: "suv",
    msrp: 42995,
    bestNewPrice: 37500,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/ford-mustang_mach-e/",
    bestUsedPrice: 28900,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/ford/mustang-mach-e",
    bestUsedYear: 2023,
    bestUsedMileage: "18k mi",
    range: 312,
    zeroToSixty: "5.1s",
    chargingSpeed: "120 mi",
    trueValueScore: 83,
    efficiency: 3.4,
    cargoSpace: "60 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 93, annual: 1116, fiveYear: 5580 },
    ownershipCost: {
      electricity5yr: 2824,
      insurance5yr: 9000,
      maintenance5yr: 4500,
      totalCost5yr: 53824,
      resalePercent: 48,
      resaleValue: 18000,
      netCost: 35824,
    },
    batteryDetails: {
      capacity: "91 kWh",
      realWorldRange: "280-300 mi",
      coldWeatherRange: "215-245 mi",
      degradationNote: "~5% at 50k mi; Ford improved battery in 2024",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/ford-mustang_mach-e/" },
      { name: "CarMax", url: "https://www.carmax.com/cars/ford/mustang-mach-e" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/ford/mustang-mach-e" },
      { name: "Carvana", url: "https://www.carvana.com/cars/ford-mustang-mach-e" },
    ],
    trendPercent: -5.5,
    trendNote: "Steep markdowns on 2024 models",
  },
  {
    id: "hyundai-ioniq-5-2024",
    brand: "Hyundai",
    model: "Ioniq 5",
    year: 2024,
    bodyType: "suv",
    msrp: 41800,
    bestNewPrice: 35200,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/hyundai/ioniq-5",
    bestUsedPrice: 27500,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/hyundai-ioniq-5",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 303,
    zeroToSixty: "5.2s",
    chargingSpeed: "180 mi",
    trueValueScore: 88,
    efficiency: 3.5,
    cargoSpace: "60 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 95, annual: 1140, fiveYear: 5700 },
    ownershipCost: {
      electricity5yr: 2743,
      insurance5yr: 8500,
      maintenance5yr: 4500,
      totalCost5yr: 50943,
      resalePercent: 50,
      resaleValue: 17600,
      netCost: 33343,
    },
    batteryDetails: {
      capacity: "77.4 kWh",
      realWorldRange: "270-295 mi",
      coldWeatherRange: "210-240 mi",
      degradationNote: "~4% at 50k mi; 800V architecture charges incredibly fast",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/hyundai/ioniq-5" },
      { name: "Carvana", url: "https://www.carvana.com/cars/hyundai-ioniq-5" },
      { name: "CarMax", url: "https://www.carmax.com/cars/hyundai/ioniq-5" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/hyundai-ioniq_5/" },
    ],
    trendPercent: -7.2,
    trendNote: "Best deals in the EV market right now",
  },
  {
    id: "kia-ev6-2024",
    brand: "Kia",
    model: "EV6 Wind",
    year: 2024,
    bodyType: "suv",
    msrp: 42600,
    bestNewPrice: 37800,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/kia-ev6/",
    bestUsedPrice: 29200,
    bestUsedPlatform: "CarGurus",
    bestUsedUrl: "https://www.cargurus.com/Cars/l-Used-Kia-EV6-d3127",
    bestUsedYear: 2023,
    bestUsedMileage: "16k mi",
    range: 310,
    zeroToSixty: "5.1s",
    chargingSpeed: "180 mi",
    trueValueScore: 86,
    efficiency: 3.5,
    cargoSpace: "50 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 95, annual: 1140, fiveYear: 5700 },
    ownershipCost: {
      electricity5yr: 2743,
      insurance5yr: 8500,
      maintenance5yr: 4500,
      totalCost5yr: 53543,
      resalePercent: 48,
      resaleValue: 18144,
      netCost: 35399,
    },
    batteryDetails: {
      capacity: "77.4 kWh",
      realWorldRange: "275-300 mi",
      coldWeatherRange: "210-240 mi",
      degradationNote: "~4% at 50k mi; same 800V platform as Ioniq 5",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/kia-ev6/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Kia-EV6-d3127" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/kia/ev6" },
      { name: "Carvana", url: "https://www.carvana.com/cars/kia-ev6" },
    ],
    trendPercent: -4.9,
    trendNote: "Competitive pricing across dealers",
  },
  {
    id: "vw-id4-2024",
    brand: "Volkswagen",
    model: "ID.4",
    year: 2024,
    bodyType: "suv",
    msrp: 39735,
    bestNewPrice: 34500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/volkswagen/id.4",
    bestUsedPrice: 25800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/volkswagen-id.4",
    bestUsedYear: 2023,
    bestUsedMileage: "20k mi",
    range: 275,
    zeroToSixty: "5.7s",
    chargingSpeed: "100 mi",
    trueValueScore: 79,
    efficiency: 3.3,
    cargoSpace: "64 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 91, annual: 1092, fiveYear: 5460 },
    ownershipCost: {
      electricity5yr: 2909,
      insurance5yr: 8000,
      maintenance5yr: 4500,
      totalCost5yr: 49909,
      resalePercent: 42,
      resaleValue: 14490,
      netCost: 35419,
    },
    batteryDetails: {
      capacity: "82 kWh",
      realWorldRange: "250-270 mi",
      coldWeatherRange: "190-220 mi",
      degradationNote: "~6% at 50k mi; VW's MEB platform is proven",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/volkswagen/id.4" },
      { name: "Carvana", url: "https://www.carvana.com/cars/volkswagen-id.4" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/volkswagen-id.4/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Volkswagen-ID.4-d3098" },
    ],
    trendPercent: -5.8,
    trendNote: "Strong incentives and dealer discounts",
  },
  {
    id: "bmw-ix-2024",
    brand: "BMW",
    model: "iX xDrive50",
    year: 2024,
    bodyType: "suv",
    msrp: 87100,
    bestNewPrice: 78000,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/bmw/ix",
    bestUsedPrice: 59500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/bmw/ix",
    bestUsedYear: 2023,
    bestUsedMileage: "12k mi",
    range: 324,
    zeroToSixty: "4.4s",
    chargingSpeed: "130 mi",
    trueValueScore: 70,
    efficiency: 3.1,
    cargoSpace: "77 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 88, annual: 1056, fiveYear: 5280 },
    ownershipCost: {
      electricity5yr: 3097,
      insurance5yr: 13000,
      maintenance5yr: 5500,
      totalCost5yr: 99597,
      resalePercent: 42,
      resaleValue: 32760,
      netCost: 66837,
    },
    batteryDetails: {
      capacity: "111.5 kWh",
      realWorldRange: "290-315 mi",
      coldWeatherRange: "225-260 mi",
      degradationNote: "~5% at 50k mi; BMW's 5th gen eDrive tech",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/bmw/ix" },
      { name: "CarMax", url: "https://www.carmax.com/cars/bmw/ix" },
      { name: "Carvana", url: "https://www.carvana.com/cars/bmw-ix" },
    ],
    trendPercent: -8.3,
    trendNote: "Luxury EVs seeing biggest drops",
  },
  {
    id: "mercedes-eqs-suv-2024",
    brand: "Mercedes",
    model: "EQS SUV",
    year: 2024,
    bodyType: "suv",
    msrp: 104400,
    bestNewPrice: 94000,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/mercedes_benz-eqs_450_plus/",
    bestUsedPrice: 72000,
    bestUsedPlatform: "AutoTrader",
    bestUsedUrl: "https://www.autotrader.com/cars-for-sale/mercedes-benz/eqs-class",
    bestUsedYear: 2023,
    bestUsedMileage: "10k mi",
    range: 305,
    zeroToSixty: "4.5s",
    chargingSpeed: "120 mi",
    trueValueScore: 65,
    efficiency: 2.9,
    cargoSpace: "74 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 85, annual: 1020, fiveYear: 5100 },
    ownershipCost: {
      electricity5yr: 3310,
      insurance5yr: 15000,
      maintenance5yr: 6000,
      totalCost5yr: 118310,
      resalePercent: 40,
      resaleValue: 37600,
      netCost: 80710,
    },
    batteryDetails: {
      capacity: "108.4 kWh",
      realWorldRange: "270-295 mi",
      coldWeatherRange: "210-245 mi",
      degradationNote: "~5% at 50k mi; premium battery management system",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/mercedes_benz-eqs_450_plus/" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/mercedes-benz/eqs-class" },
      { name: "CarMax", url: "https://www.carmax.com/cars/mercedes-benz/eqs450+" },
    ],
    trendPercent: -9.0,
    trendNote: "Massive depreciation on luxury EVs",
  },
  {
    id: "toyota-bz4x-2024",
    brand: "Toyota",
    model: "bZ4X",
    year: 2024,
    bodyType: "suv",
    msrp: 42000,
    bestNewPrice: 33500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/toyota/bz4x",
    bestUsedPrice: 24800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/toyota-bz4x",
    bestUsedYear: 2023,
    bestUsedMileage: "18k mi",
    range: 252,
    zeroToSixty: "6.6s",
    chargingSpeed: "80 mi",
    trueValueScore: 81,
    efficiency: 3.1,
    cargoSpace: "60 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 10yr/150k battery",
    fuelSavings: { monthly: 88, annual: 1056, fiveYear: 5280 },
    ownershipCost: {
      electricity5yr: 3097,
      insurance5yr: 8500,
      maintenance5yr: 4500,
      totalCost5yr: 49597,
      resalePercent: 48,
      resaleValue: 16080,
      netCost: 33517,
    },
    batteryDetails: {
      capacity: "71.4 kWh",
      realWorldRange: "225-245 mi",
      coldWeatherRange: "175-205 mi",
      degradationNote: "Toyota's 10yr/150k warranty shows battery confidence",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/toyota/bz4x" },
      { name: "Carvana", url: "https://www.carvana.com/cars/toyota-bz4x" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/toyota-bz4x/" },
    ],
    trendPercent: -9.5,
    trendNote: "Deep discounts to move inventory",
  },
  {
    id: "nissan-ariya-2024",
    brand: "Nissan",
    model: "Ariya",
    year: 2024,
    bodyType: "suv",
    msrp: 39590,
    bestNewPrice: 33200,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/nissan-ariya/",
    bestUsedPrice: 26500,
    bestUsedPlatform: "CarGurus",
    bestUsedUrl: "https://www.cargurus.com/Cars/l-Used-Nissan-Ariya-d3216",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 304,
    zeroToSixty: "5.9s",
    chargingSpeed: "100 mi",
    trueValueScore: 84,
    efficiency: 3.4,
    cargoSpace: "59 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 93, annual: 1116, fiveYear: 5580 },
    ownershipCost: {
      electricity5yr: 2824,
      insurance5yr: 8000,
      maintenance5yr: 4500,
      totalCost5yr: 48524,
      resalePercent: 42,
      resaleValue: 13950,
      netCost: 34574,
    },
    batteryDetails: {
      capacity: "87 kWh",
      realWorldRange: "270-295 mi",
      coldWeatherRange: "210-240 mi",
      degradationNote: "~5% at 50k mi; liquid-cooled, much better than Leaf",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/nissan-ariya/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Nissan-Ariya-d3216" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/nissan/ariya" },
    ],
    trendPercent: -6.8,
    trendNote: "Undervalued — strong specs for the price",
  },
  {
    id: "chevy-blazer-ev-2024",
    brand: "Chevrolet",
    model: "Blazer EV",
    year: 2024,
    bodyType: "suv",
    msrp: 45595,
    bestNewPrice: 38000,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/chevrolet/blazer-ev",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 279,
    zeroToSixty: "5.6s",
    chargingSpeed: "120 mi",
    trueValueScore: 76,
    efficiency: 3.2,
    cargoSpace: "55 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 90, annual: 1080, fiveYear: 5400 },
    ownershipCost: {
      electricity5yr: 3000,
      insurance5yr: 9000,
      maintenance5yr: 4500,
      totalCost5yr: 54500,
      resalePercent: 45,
      resaleValue: 17100,
      netCost: 37400,
    },
    batteryDetails: {
      capacity: "85 kWh",
      realWorldRange: "250-270 mi",
      coldWeatherRange: "195-225 mi",
      degradationNote: "Too new for data; Ultium platform shared with Equinox EV",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/chevrolet/blazer-ev" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/chevrolet-blazer_ev/" },
    ],
    trendPercent: -4.5,
    trendNote: "Post-recall prices stabilizing with discounts",
  },
  {
    id: "rivian-r1s-2024",
    brand: "Rivian",
    model: "R1S",
    year: 2024,
    bodyType: "suv",
    msrp: 75900,
    bestNewPrice: 75900,
    bestNewPlatform: "Rivian.com",
    bestNewUrl: "https://rivian.com/r1s",
    bestUsedPrice: 62000,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/rivian/r1s",
    bestUsedYear: 2023,
    bestUsedMileage: "12k mi",
    range: 321,
    zeroToSixty: "3.0s",
    chargingSpeed: "140 mi",
    trueValueScore: 71,
    efficiency: 2.8,
    cargoSpace: "104 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 8yr/175k battery",
    fuelSavings: { monthly: 82, annual: 984, fiveYear: 4920 },
    ownershipCost: {
      electricity5yr: 3429,
      insurance5yr: 11500,
      maintenance5yr: 4500,
      totalCost5yr: 95329,
      resalePercent: 55,
      resaleValue: 41745,
      netCost: 53584,
    },
    batteryDetails: {
      capacity: "135 kWh",
      realWorldRange: "285-310 mi",
      coldWeatherRange: "225-260 mi",
      degradationNote: "~4% at 50k mi; massive battery pack with great longevity",
    },
    platforms: [
      { name: "Rivian.com", url: "https://rivian.com/r1s" },
      { name: "CarMax", url: "https://www.carmax.com/cars/rivian/r1s" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/rivian/r1s" },
    ],
    trendPercent: 2.1,
    trendNote: "Limited supply keeping prices firm",
  },
  {
    id: "kia-ev9-2024",
    brand: "Kia",
    model: "EV9",
    year: 2024,
    bodyType: "suv",
    msrp: 54900,
    bestNewPrice: 49500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/kia/ev9",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 304,
    zeroToSixty: "5.0s",
    chargingSpeed: "180 mi",
    trueValueScore: 77,
    efficiency: 3.0,
    cargoSpace: "82 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 87, annual: 1044, fiveYear: 5220 },
    ownershipCost: {
      electricity5yr: 3200,
      insurance5yr: 9500,
      maintenance5yr: 4500,
      totalCost5yr: 66700,
      resalePercent: 50,
      resaleValue: 24750,
      netCost: 41950,
    },
    batteryDetails: {
      capacity: "99.8 kWh",
      realWorldRange: "270-295 mi",
      coldWeatherRange: "210-245 mi",
      degradationNote: "Too new for data; 800V architecture with 10yr warranty",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/kia/ev9" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/kia-ev9/" },
    ],
    trendPercent: -3.5,
    trendNote: "Three-row EV with growing availability",
  },
  {
    id: "subaru-solterra-2024",
    brand: "Subaru",
    model: "Solterra",
    year: 2024,
    bodyType: "suv",
    msrp: 44995,
    bestNewPrice: 36000,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/subaru-solterra/",
    bestUsedPrice: 26500,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/subaru-solterra",
    bestUsedYear: 2023,
    bestUsedMileage: "20k mi",
    range: 228,
    zeroToSixty: "6.5s",
    chargingSpeed: "80 mi",
    trueValueScore: 74,
    efficiency: 3.0,
    cargoSpace: "53 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 87, annual: 1044, fiveYear: 5220 },
    ownershipCost: {
      electricity5yr: 3200,
      insurance5yr: 8500,
      maintenance5yr: 4500,
      totalCost5yr: 52200,
      resalePercent: 40,
      resaleValue: 14400,
      netCost: 37800,
    },
    batteryDetails: {
      capacity: "71.4 kWh",
      realWorldRange: "200-220 mi",
      coldWeatherRange: "160-185 mi",
      degradationNote: "Same platform as bZ4X; AWD standard",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/subaru-solterra/" },
      { name: "Carvana", url: "https://www.carvana.com/cars/subaru-solterra" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/subaru/solterra" },
    ],
    trendPercent: -8.0,
    trendNote: "Big dealer markdowns to compete",
  },

  // === TRUCKS ===
  {
    id: "ford-f150-lightning-2024",
    brand: "Ford",
    model: "F-150 Lightning",
    year: 2024,
    bodyType: "truck",
    msrp: 49995,
    bestNewPrice: 44000,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/ford/f150-lightning",
    bestUsedPrice: 36500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/ford/f150-lightning",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 300,
    zeroToSixty: "4.0s",
    chargingSpeed: "120 mi",
    trueValueScore: 80,
    efficiency: 2.5,
    cargoSpace: "52 cu ft + frunk",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 130, annual: 1560, fiveYear: 7800 },
    ownershipCost: {
      electricity5yr: 3840,
      insurance5yr: 10000,
      maintenance5yr: 5000,
      totalCost5yr: 62840,
      resalePercent: 48,
      resaleValue: 21120,
      netCost: 41720,
    },
    batteryDetails: {
      capacity: "98 kWh",
      realWorldRange: "260-290 mi",
      coldWeatherRange: "200-235 mi",
      degradationNote: "~5% at 50k mi; towing significantly reduces range",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/ford/f150-lightning" },
      { name: "CarMax", url: "https://www.carmax.com/cars/ford/f150-lightning" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/ford-f_150_lightning/" },
      { name: "Carvana", url: "https://www.carvana.com/cars/ford-f-150-lightning" },
    ],
    trendPercent: -5.5,
    trendNote: "Electric truck prices falling fast",
  },
  {
    id: "rivian-r1t-2024",
    brand: "Rivian",
    model: "R1T",
    year: 2024,
    bodyType: "truck",
    msrp: 69900,
    bestNewPrice: 69900,
    bestNewPlatform: "Rivian.com",
    bestNewUrl: "https://rivian.com/r1t",
    bestUsedPrice: 55000,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/rivian-r1t",
    bestUsedYear: 2023,
    bestUsedMileage: "18k mi",
    range: 328,
    zeroToSixty: "3.0s",
    chargingSpeed: "140 mi",
    trueValueScore: 73,
    efficiency: 2.6,
    cargoSpace: "68 cu ft + bed",
    warranty: "5yr/60k bumper-to-bumper, 8yr/175k battery",
    fuelSavings: { monthly: 128, annual: 1536, fiveYear: 7680 },
    ownershipCost: {
      electricity5yr: 3692,
      insurance5yr: 11000,
      maintenance5yr: 4500,
      totalCost5yr: 89092,
      resalePercent: 52,
      resaleValue: 36348,
      netCost: 52744,
    },
    batteryDetails: {
      capacity: "135 kWh",
      realWorldRange: "290-320 mi",
      coldWeatherRange: "230-265 mi",
      degradationNote: "~4% at 50k mi; adventure-focused battery design",
    },
    platforms: [
      { name: "Rivian.com", url: "https://rivian.com/r1t" },
      { name: "Carvana", url: "https://www.carvana.com/cars/rivian-r1t" },
      { name: "CarMax", url: "https://www.carmax.com/cars/rivian/r1t" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/rivian/r1t" },
    ],
    trendPercent: 1.5,
    trendNote: "Demand holding steady for adventure truck",
  },
  {
    id: "chevy-silverado-ev-2024",
    brand: "Chevrolet",
    model: "Silverado EV",
    year: 2024,
    bodyType: "truck",
    msrp: 49995,
    bestNewPrice: 45000,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/chevrolet/silverado-ev",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 390,
    zeroToSixty: "4.5s",
    chargingSpeed: "150 mi",
    trueValueScore: 82,
    efficiency: 2.7,
    cargoSpace: "60 cu ft + bed",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 130, annual: 1560, fiveYear: 7800 },
    ownershipCost: {
      electricity5yr: 3556,
      insurance5yr: 10000,
      maintenance5yr: 5000,
      totalCost5yr: 63556,
      resalePercent: 48,
      resaleValue: 21600,
      netCost: 41956,
    },
    batteryDetails: {
      capacity: "200 kWh",
      realWorldRange: "350-380 mi",
      coldWeatherRange: "275-310 mi",
      degradationNote: "Massive battery; too new for long-term data",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/chevrolet/silverado-ev" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/chevrolet-silverado_ev/" },
    ],
    trendPercent: -3.0,
    trendNote: "New to market with introductory pricing",
  },
  {
    id: "tesla-cybertruck-2024",
    brand: "Tesla",
    model: "Cybertruck",
    year: 2024,
    bodyType: "truck",
    msrp: 79990,
    bestNewPrice: 79990,
    bestNewPlatform: "Tesla.com",
    bestNewUrl: "https://www.tesla.com/cybertruck",
    bestUsedPrice: 85000,
    bestUsedPlatform: "CarGurus",
    bestUsedUrl: "https://www.cargurus.com/Cars/l-Used-Tesla-Cybertruck-d3353",
    bestUsedYear: 2024,
    bestUsedMileage: "5k mi",
    range: 340,
    zeroToSixty: "2.6s",
    chargingSpeed: "136 mi",
    trueValueScore: 55,
    efficiency: 2.5,
    cargoSpace: "68 cu ft + bed",
    warranty: "4yr/50k bumper-to-bumper, 8yr/150k battery",
    fuelSavings: { monthly: 130, annual: 1560, fiveYear: 7800 },
    ownershipCost: {
      electricity5yr: 3840,
      insurance5yr: 12000,
      maintenance5yr: 5000,
      totalCost5yr: 100830,
      resalePercent: 60,
      resaleValue: 47994,
      netCost: 52836,
    },
    batteryDetails: {
      capacity: "123 kWh",
      realWorldRange: "300-330 mi",
      coldWeatherRange: "235-275 mi",
      degradationNote: "Too new; early reports show typical Tesla longevity",
    },
    platforms: [
      { name: "Tesla.com", url: "https://www.tesla.com/cybertruck" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Tesla-Cybertruck-d3353" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/tesla/cybertruck" },
    ],
    trendPercent: 0,
    trendNote: "Used prices above MSRP due to demand",
  },

  // === HATCHBACK ===
  {
    id: "chevy-bolt-euv-2023",
    brand: "Chevrolet",
    model: "Bolt EUV",
    year: 2023,
    bodyType: "hatchback",
    msrp: 28795,
    bestNewPrice: null,
    bestNewPlatform: null,
    bestNewUrl: "",
    bestUsedPrice: 19800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/chevrolet-bolt-euv",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 247,
    zeroToSixty: "6.5s",
    chargingSpeed: "75 mi",
    trueValueScore: 91,
    efficiency: 3.7,
    cargoSpace: "57 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 94, annual: 1128, fiveYear: 5640 },
    ownershipCost: {
      electricity5yr: 2595,
      insurance5yr: 7000,
      maintenance5yr: 4000,
      totalCost5yr: 33395,
      resalePercent: 35,
      resaleValue: 6930,
      netCost: 26465,
    },
    batteryDetails: {
      capacity: "65 kWh",
      realWorldRange: "220-240 mi",
      coldWeatherRange: "170-195 mi",
      degradationNote: "New battery pack (post-recall); excellent value",
    },
    platforms: [
      { name: "Carvana", url: "https://www.carvana.com/cars/chevrolet-bolt-euv" },
      { name: "CarMax", url: "https://www.carmax.com/cars/chevrolet/bolt-euv" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Chevrolet-Bolt-EUV-d3116" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/chevrolet/bolt-euv" },
    ],
    trendPercent: -3.0,
    trendNote: "Discontinued but incredible used value",
    discontinued: true,
  },

  // === NEW SEDANS ===
  {
    id: "hyundai-ioniq-6-2024",
    brand: "Hyundai",
    model: "Ioniq 6",
    year: 2024,
    bodyType: "sedan",
    msrp: 42450,
    bestNewPrice: 38200,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/hyundai/ioniq-6",
    bestUsedPrice: 33500,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/hyundai-ioniq-6",
    bestUsedYear: 2023,
    bestUsedMileage: "12k mi",
    range: 361,
    zeroToSixty: "5.1s",
    chargingSpeed: "180 mi",
    trueValueScore: 87,
    efficiency: 3.5,
    cargoSpace: "12 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 98, annual: 1176, fiveYear: 5880 },
    ownershipCost: {
      electricity5yr: 2400,
      insurance5yr: 8500,
      maintenance5yr: 4200,
      totalCost5yr: 53300,
      resalePercent: 50,
      resaleValue: 21225,
      netCost: 32075,
    },
    batteryDetails: {
      capacity: "77.4 kWh",
      realWorldRange: "330-355 mi",
      coldWeatherRange: "255-285 mi",
      degradationNote: "800V architecture enables ultra-fast charging; ~4% loss at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/hyundai/ioniq-6" },
      { name: "Carvana", url: "https://www.carvana.com/cars/hyundai-ioniq-6" },
      { name: "CarMax", url: "https://www.carmax.com/cars/hyundai/ioniq-6" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/hyundai-ioniq_6/" },
    ],
    trendPercent: -5.8,
    trendNote: "Sleek sedan with incredible efficiency",
  },
  {
    id: "dodge-charger-daytona-2024",
    brand: "Dodge",
    model: "Charger Daytona",
    year: 2024,
    bodyType: "sedan",
    msrp: 59595,
    bestNewPrice: 54900,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/dodge/charger-daytona",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 317,
    zeroToSixty: "4.7s",
    chargingSpeed: "150 mi",
    trueValueScore: 72,
    efficiency: 2.8,
    cargoSpace: "16 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 80, annual: 960, fiveYear: 4800 },
    ownershipCost: {
      electricity5yr: 3100,
      insurance5yr: 10500,
      maintenance5yr: 4800,
      totalCost5yr: 73295,
      resalePercent: 45,
      resaleValue: 26818,
      netCost: 46477,
    },
    batteryDetails: {
      capacity: "100.5 kWh",
      realWorldRange: "285-310 mi",
      coldWeatherRange: "220-250 mi",
      degradationNote: "New platform; Dodge's first EV — long-term data pending",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/dodge/charger-daytona" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/dodge-charger_daytona/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Dodge-Charger-Daytona" },
    ],
    trendPercent: -2.1,
    trendNote: "New launch — limited discounts so far",
  },
  {
    id: "porsche-taycan-2024",
    brand: "Porsche",
    model: "Taycan",
    year: 2024,
    bodyType: "sedan",
    msrp: 92250,
    bestNewPrice: 85500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/porsche/taycan",
    bestUsedPrice: 68900,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/porsche/taycan",
    bestUsedYear: 2023,
    bestUsedMileage: "14k mi",
    range: 318,
    zeroToSixty: "3.8s",
    chargingSpeed: "175 mi",
    trueValueScore: 66,
    efficiency: 2.9,
    cargoSpace: "15 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 78, annual: 936, fiveYear: 4680 },
    ownershipCost: {
      electricity5yr: 3200,
      insurance5yr: 14000,
      maintenance5yr: 6000,
      totalCost5yr: 108700,
      resalePercent: 42,
      resaleValue: 38745,
      netCost: 69955,
    },
    batteryDetails: {
      capacity: "93.4 kWh",
      realWorldRange: "285-310 mi",
      coldWeatherRange: "220-250 mi",
      degradationNote: "~4% loss at 50k mi; Porsche's premium battery management",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/porsche/taycan" },
      { name: "CarMax", url: "https://www.carmax.com/cars/porsche/taycan" },
      { name: "Carvana", url: "https://www.carvana.com/cars/porsche-taycan" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/porsche-taycan/" },
    ],
    trendPercent: -6.5,
    trendNote: "Luxury EV depreciation creating used bargains",
  },

  // === NEW SUVs ===
  {
    id: "honda-prologue-2024",
    brand: "Honda",
    model: "Prologue",
    year: 2024,
    bodyType: "suv",
    msrp: 47400,
    bestNewPrice: 42500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/honda/prologue",
    bestUsedPrice: 37800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/honda-prologue",
    bestUsedYear: 2024,
    bestUsedMileage: "8k mi",
    range: 296,
    zeroToSixty: "5.5s",
    chargingSpeed: "140 mi",
    trueValueScore: 83,
    efficiency: 3.1,
    cargoSpace: "72 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 88, annual: 1056, fiveYear: 5280 },
    ownershipCost: {
      electricity5yr: 2700,
      insurance5yr: 8800,
      maintenance5yr: 4200,
      totalCost5yr: 58100,
      resalePercent: 48,
      resaleValue: 22752,
      netCost: 35348,
    },
    batteryDetails: {
      capacity: "85 kWh (Ultium)",
      realWorldRange: "270-290 mi",
      coldWeatherRange: "210-240 mi",
      degradationNote: "GM Ultium platform — early data shows solid reliability",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/honda/prologue" },
      { name: "Carvana", url: "https://www.carvana.com/cars/honda-prologue" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/honda-prologue/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Honda-Prologue" },
    ],
    trendPercent: -4.5,
    trendNote: "Honda's first EV gaining dealer momentum",
    featured: true,
    featuredNote: "Honda's first mainstream EV — strong value with Ultium platform reliability.",
  },
  {
    id: "acura-zdx-2024",
    brand: "Acura",
    model: "ZDX",
    year: 2024,
    bodyType: "suv",
    msrp: 64500,
    bestNewPrice: 58900,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/acura/zdx",
    bestUsedPrice: 52500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/acura/zdx",
    bestUsedYear: 2024,
    bestUsedMileage: "10k mi",
    range: 313,
    zeroToSixty: "5.0s",
    chargingSpeed: "145 mi",
    trueValueScore: 73,
    efficiency: 2.9,
    cargoSpace: "69 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 82, annual: 984, fiveYear: 4920 },
    ownershipCost: {
      electricity5yr: 2900,
      insurance5yr: 10800,
      maintenance5yr: 4800,
      totalCost5yr: 76600,
      resalePercent: 44,
      resaleValue: 28380,
      netCost: 48220,
    },
    batteryDetails: {
      capacity: "102 kWh (Ultium)",
      realWorldRange: "285-305 mi",
      coldWeatherRange: "220-250 mi",
      degradationNote: "Ultium platform shared with Honda Prologue; solid early results",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/acura/zdx" },
      { name: "CarMax", url: "https://www.carmax.com/cars/acura/zdx" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/acura-zdx/" },
    ],
    trendPercent: -3.8,
    trendNote: "Premium alternative to Honda Prologue — discounts increasing",
  },
  {
    id: "cadillac-lyriq-2024",
    brand: "Cadillac",
    model: "Lyriq",
    year: 2024,
    bodyType: "suv",
    msrp: 57195,
    bestNewPrice: 50900,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/cadillac/lyriq",
    bestUsedPrice: 44200,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/cadillac/lyriq",
    bestUsedYear: 2023,
    bestUsedMileage: "14k mi",
    range: 314,
    zeroToSixty: "5.7s",
    chargingSpeed: "140 mi",
    trueValueScore: 75,
    efficiency: 3.0,
    cargoSpace: "60 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 86, annual: 1032, fiveYear: 5160 },
    ownershipCost: {
      electricity5yr: 2800,
      insurance5yr: 10000,
      maintenance5yr: 4600,
      totalCost5yr: 68195,
      resalePercent: 43,
      resaleValue: 24594,
      netCost: 43601,
    },
    batteryDetails: {
      capacity: "102 kWh",
      realWorldRange: "285-310 mi",
      coldWeatherRange: "220-250 mi",
      degradationNote: "GM Ultium platform — proven chemistry with good longevity",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/cadillac/lyriq" },
      { name: "CarMax", url: "https://www.carmax.com/cars/cadillac/lyriq" },
      { name: "Carvana", url: "https://www.carvana.com/cars/cadillac-lyriq" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/cadillac-lyriq/" },
    ],
    trendPercent: -5.2,
    trendNote: "Strong discounts on dealer lots — luxury for less",
  },
  {
    id: "cadillac-escalade-iq-2025",
    brand: "Cadillac",
    model: "Escalade IQ",
    year: 2025,
    bodyType: "suv",
    msrp: 129990,
    bestNewPrice: 124500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/cadillac/escalade-iq",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 460,
    zeroToSixty: "4.9s",
    chargingSpeed: "200 mi",
    trueValueScore: 60,
    efficiency: 2.1,
    cargoSpace: "121 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 105, annual: 1260, fiveYear: 6300 },
    ownershipCost: {
      electricity5yr: 4200,
      insurance5yr: 16000,
      maintenance5yr: 6500,
      totalCost5yr: 156690,
      resalePercent: 40,
      resaleValue: 51996,
      netCost: 104694,
    },
    batteryDetails: {
      capacity: "200 kWh",
      realWorldRange: "420-450 mi",
      coldWeatherRange: "330-370 mi",
      degradationNote: "Massive Ultium pack; GM's largest battery — excellent highway range",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/cadillac/escalade-iq" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/cadillac-escalade_iq/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Cadillac-Escalade-IQ" },
    ],
    trendPercent: -1.2,
    trendNote: "New flagship — limited supply, minimal discounts",
  },
  {
    id: "genesis-gv60-2024",
    brand: "Genesis",
    model: "GV60",
    year: 2024,
    bodyType: "suv",
    msrp: 52000,
    bestNewPrice: 45500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/genesis/gv60",
    bestUsedPrice: 38200,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/genesis-gv60",
    bestUsedYear: 2023,
    bestUsedMileage: "16k mi",
    range: 248,
    zeroToSixty: "4.0s",
    chargingSpeed: "165 mi",
    trueValueScore: 74,
    efficiency: 3.0,
    cargoSpace: "54 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 84, annual: 1008, fiveYear: 5040 },
    ownershipCost: {
      electricity5yr: 2650,
      insurance5yr: 9500,
      maintenance5yr: 4400,
      totalCost5yr: 62050,
      resalePercent: 42,
      resaleValue: 21840,
      netCost: 40210,
    },
    batteryDetails: {
      capacity: "77.4 kWh",
      realWorldRange: "225-245 mi",
      coldWeatherRange: "175-200 mi",
      degradationNote: "800V architecture; ultra-fast 10-80% in 18 min — ~5% loss at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/genesis/gv60" },
      { name: "Carvana", url: "https://www.carvana.com/cars/genesis-gv60" },
      { name: "CarMax", url: "https://www.carmax.com/cars/genesis/gv60" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/genesis-gv60/" },
    ],
    trendPercent: -6.0,
    trendNote: "Underrated luxury EV — steep depreciation means great deals",
  },
  {
    id: "genesis-egv70-2024",
    brand: "Genesis",
    model: "Electrified GV70",
    year: 2024,
    bodyType: "suv",
    msrp: 65850,
    bestNewPrice: 59200,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/genesis/electrified-gv70",
    bestUsedPrice: 48500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/genesis/electrified-gv70",
    bestUsedYear: 2023,
    bestUsedMileage: "18k mi",
    range: 236,
    zeroToSixty: "4.2s",
    chargingSpeed: "155 mi",
    trueValueScore: 69,
    efficiency: 2.8,
    cargoSpace: "56 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 79, annual: 948, fiveYear: 4740 },
    ownershipCost: {
      electricity5yr: 2900,
      insurance5yr: 11000,
      maintenance5yr: 4600,
      totalCost5yr: 78350,
      resalePercent: 40,
      resaleValue: 26340,
      netCost: 52010,
    },
    batteryDetails: {
      capacity: "77.4 kWh",
      realWorldRange: "210-230 mi",
      coldWeatherRange: "165-190 mi",
      degradationNote: "Shared platform with GV60; solid 800V charging — ~5% at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/genesis/electrified-gv70" },
      { name: "CarMax", url: "https://www.carmax.com/cars/genesis/electrified-gv70" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/genesis-electrified_gv70/" },
    ],
    trendPercent: -5.5,
    trendNote: "Luxury EV crossover seeing significant dealer incentives",
  },
  {
    id: "volvo-ex30-2024",
    brand: "Volvo",
    model: "EX30",
    year: 2024,
    bodyType: "suv",
    msrp: 34950,
    bestNewPrice: 32500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/volvo/ex30",
    bestUsedPrice: 29800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/volvo-ex30",
    bestUsedYear: 2024,
    bestUsedMileage: "6k mi",
    range: 275,
    zeroToSixty: "5.1s",
    chargingSpeed: "130 mi",
    trueValueScore: 86,
    efficiency: 3.6,
    cargoSpace: "44 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 95, annual: 1140, fiveYear: 5700 },
    ownershipCost: {
      electricity5yr: 2300,
      insurance5yr: 7800,
      maintenance5yr: 4000,
      totalCost5yr: 46600,
      resalePercent: 48,
      resaleValue: 16776,
      netCost: 29824,
    },
    batteryDetails: {
      capacity: "69 kWh",
      realWorldRange: "250-270 mi",
      coldWeatherRange: "195-220 mi",
      degradationNote: "Compact battery with solid energy density; ~5% loss at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/volvo/ex30" },
      { name: "Carvana", url: "https://www.carvana.com/cars/volvo-ex30" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/volvo-ex30/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Volvo-EX30" },
    ],
    trendPercent: -3.5,
    trendNote: "Affordable Volvo EV — inventory growing, deals improving",
  },
  {
    id: "volvo-ex90-2024",
    brand: "Volvo",
    model: "EX90",
    year: 2024,
    bodyType: "suv",
    msrp: 79995,
    bestNewPrice: 73500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/volvo/ex90",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 310,
    zeroToSixty: "4.9s",
    chargingSpeed: "155 mi",
    trueValueScore: 70,
    efficiency: 2.6,
    cargoSpace: "74 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 82, annual: 984, fiveYear: 4920 },
    ownershipCost: {
      electricity5yr: 3200,
      insurance5yr: 12500,
      maintenance5yr: 5200,
      totalCost5yr: 94395,
      resalePercent: 42,
      resaleValue: 33598,
      netCost: 60797,
    },
    batteryDetails: {
      capacity: "111 kWh",
      realWorldRange: "280-305 mi",
      coldWeatherRange: "220-250 mi",
      degradationNote: "Large battery pack with bi-directional charging; new platform — data pending",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/volvo/ex90" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/volvo-ex90/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Volvo-EX90" },
    ],
    trendPercent: -2.8,
    trendNote: "New flagship — early adopter deals starting to appear",
  },
  {
    id: "audi-q4-etron-2024",
    brand: "Audi",
    model: "Q4 e-tron",
    year: 2024,
    bodyType: "suv",
    msrp: 49800,
    bestNewPrice: 43500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/audi/q4-e-tron",
    bestUsedPrice: 36800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/audi-q4-e-tron",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 265,
    zeroToSixty: "5.8s",
    chargingSpeed: "130 mi",
    trueValueScore: 73,
    efficiency: 3.0,
    cargoSpace: "53 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 83, annual: 996, fiveYear: 4980 },
    ownershipCost: {
      electricity5yr: 2750,
      insurance5yr: 9800,
      maintenance5yr: 5000,
      totalCost5yr: 62350,
      resalePercent: 40,
      resaleValue: 19920,
      netCost: 42430,
    },
    batteryDetails: {
      capacity: "82 kWh",
      realWorldRange: "240-260 mi",
      coldWeatherRange: "185-215 mi",
      degradationNote: "MEB platform; reliable battery — ~5% loss at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/audi/q4-e-tron" },
      { name: "Carvana", url: "https://www.carvana.com/cars/audi-q4-e-tron" },
      { name: "CarMax", url: "https://www.carmax.com/cars/audi/q4-e-tron" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/audi-q4_e-tron/" },
    ],
    trendPercent: -5.8,
    trendNote: "Solid discounts on compact luxury EV",
  },
  {
    id: "audi-q8-etron-2024",
    brand: "Audi",
    model: "Q8 e-tron",
    year: 2024,
    bodyType: "suv",
    msrp: 74400,
    bestNewPrice: 66500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/audi/q8-e-tron",
    bestUsedPrice: 54800,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/audi/q8-e-tron",
    bestUsedYear: 2023,
    bestUsedMileage: "16k mi",
    range: 285,
    zeroToSixty: "5.6s",
    chargingSpeed: "140 mi",
    trueValueScore: 67,
    efficiency: 2.5,
    cargoSpace: "57 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 76, annual: 912, fiveYear: 4560 },
    ownershipCost: {
      electricity5yr: 3300,
      insurance5yr: 12000,
      maintenance5yr: 5500,
      totalCost5yr: 87200,
      resalePercent: 38,
      resaleValue: 28272,
      netCost: 58928,
    },
    batteryDetails: {
      capacity: "114 kWh",
      realWorldRange: "260-280 mi",
      coldWeatherRange: "200-230 mi",
      degradationNote: "Revised from e-tron; larger battery with improved efficiency — ~5% at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/audi/q8-e-tron" },
      { name: "CarMax", url: "https://www.carmax.com/cars/audi/q8-e-tron" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/audi-q8_e-tron/" },
    ],
    trendPercent: -7.5,
    trendNote: "Steep depreciation on luxury EV — great used deals",
  },
  {
    id: "porsche-macan-electric-2025",
    brand: "Porsche",
    model: "Macan Electric",
    year: 2025,
    bodyType: "suv",
    msrp: 72800,
    bestNewPrice: 69500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/porsche/macan-electric",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 308,
    zeroToSixty: "4.1s",
    chargingSpeed: "170 mi",
    trueValueScore: 68,
    efficiency: 2.8,
    cargoSpace: "52 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 80, annual: 960, fiveYear: 4800 },
    ownershipCost: {
      electricity5yr: 3100,
      insurance5yr: 13000,
      maintenance5yr: 5800,
      totalCost5yr: 91400,
      resalePercent: 45,
      resaleValue: 32760,
      netCost: 58640,
    },
    batteryDetails: {
      capacity: "100 kWh",
      realWorldRange: "280-300 mi",
      coldWeatherRange: "220-250 mi",
      degradationNote: "PPE platform shared with Audi; 800V architecture — long-term data pending",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/porsche/macan-electric" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/porsche-macan_electric/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Porsche-Macan-Electric" },
    ],
    trendPercent: -1.5,
    trendNote: "Brand new model — high demand keeping prices firm",
  },
  {
    id: "hyundai-ioniq-9-2026",
    brand: "Hyundai",
    model: "Ioniq 9",
    year: 2026,
    bodyType: "suv",
    msrp: 55000,
    bestNewPrice: null,
    bestNewPlatform: null,
    bestNewUrl: "",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 350,
    zeroToSixty: "5.2s",
    chargingSpeed: "175 mi",
    trueValueScore: 80,
    efficiency: 3.0,
    cargoSpace: "87 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 90, annual: 1080, fiveYear: 5400 },
    ownershipCost: {
      electricity5yr: 2800,
      insurance5yr: 9200,
      maintenance5yr: 4400,
      totalCost5yr: 66400,
      resalePercent: 46,
      resaleValue: 25300,
      netCost: 41100,
    },
    batteryDetails: {
      capacity: "110 kWh",
      realWorldRange: "320-345 mi",
      coldWeatherRange: "250-280 mi",
      degradationNote: "800V E-GMP platform; 3-row SUV — expected excellent efficiency",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/hyundai/ioniq-9" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/hyundai-ioniq_9/" },
    ],
    trendPercent: 0.0,
    trendNote: "Not yet available — pricing is estimated MSRP",
  },
  {
    id: "lexus-rz-450e-2024",
    brand: "Lexus",
    model: "RZ 450e",
    year: 2024,
    bodyType: "suv",
    msrp: 55150,
    bestNewPrice: 47500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/lexus/rz",
    bestUsedPrice: 39800,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/lexus/rz",
    bestUsedYear: 2023,
    bestUsedMileage: "12k mi",
    range: 220,
    zeroToSixty: "5.3s",
    chargingSpeed: "100 mi",
    trueValueScore: 65,
    efficiency: 2.8,
    cargoSpace: "57 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 10yr/unlimited battery",
    fuelSavings: { monthly: 75, annual: 900, fiveYear: 4500 },
    ownershipCost: {
      electricity5yr: 2900,
      insurance5yr: 10200,
      maintenance5yr: 4800,
      totalCost5yr: 67050,
      resalePercent: 40,
      resaleValue: 22060,
      netCost: 44990,
    },
    batteryDetails: {
      capacity: "71.4 kWh",
      realWorldRange: "195-215 mi",
      coldWeatherRange: "150-175 mi",
      degradationNote: "Toyota's 10yr/unlimited battery warranty — conservative chemistry prioritizes longevity",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/lexus/rz" },
      { name: "CarMax", url: "https://www.carmax.com/cars/lexus/rz" },
      { name: "Carvana", url: "https://www.carvana.com/cars/lexus-rz" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/lexus-rz/" },
    ],
    trendPercent: -8.2,
    trendNote: "Low range hurting resale — deep discounts available",
  },
  {
    id: "lucid-gravity-2025",
    brand: "Lucid",
    model: "Gravity",
    year: 2025,
    bodyType: "suv",
    msrp: 79900,
    bestNewPrice: 76500,
    bestNewPlatform: "Lucid.com",
    bestNewUrl: "https://www.lucidmotors.com/gravity",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 440,
    zeroToSixty: "3.5s",
    chargingSpeed: "200 mi",
    trueValueScore: 74,
    efficiency: 3.5,
    cargoSpace: "112 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 95, annual: 1140, fiveYear: 5700 },
    ownershipCost: {
      electricity5yr: 2600,
      insurance5yr: 13000,
      maintenance5yr: 5200,
      totalCost5yr: 96700,
      resalePercent: 40,
      resaleValue: 31960,
      netCost: 64740,
    },
    batteryDetails: {
      capacity: "113 kWh",
      realWorldRange: "400-430 mi",
      coldWeatherRange: "310-350 mi",
      degradationNote: "Lucid's industry-leading efficiency; 3-row SUV with class-leading range",
    },
    platforms: [
      { name: "Lucid.com", url: "https://www.lucidmotors.com/gravity" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/lucid/gravity" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/lucid-gravity/" },
    ],
    trendPercent: -1.0,
    trendNote: "Just launched — strong demand, minimal discounts",
  },
  {
    id: "jeep-wagoneer-s-2025",
    brand: "Jeep",
    model: "Wagoneer S",
    year: 2025,
    bodyType: "suv",
    msrp: 71995,
    bestNewPrice: 66500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/jeep/wagoneer-s",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 300,
    zeroToSixty: "3.4s",
    chargingSpeed: "150 mi",
    trueValueScore: 67,
    efficiency: 2.7,
    cargoSpace: "65 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 78, annual: 936, fiveYear: 4680 },
    ownershipCost: {
      electricity5yr: 3100,
      insurance5yr: 11500,
      maintenance5yr: 5200,
      totalCost5yr: 87795,
      resalePercent: 40,
      resaleValue: 28798,
      netCost: 58997,
    },
    batteryDetails: {
      capacity: "100 kWh",
      realWorldRange: "270-295 mi",
      coldWeatherRange: "210-240 mi",
      degradationNote: "STLA Large platform; Jeep's first premium EV — long-term data pending",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/jeep/wagoneer-s" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/jeep-wagoneer_s/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Jeep-Wagoneer-S" },
    ],
    trendPercent: -2.5,
    trendNote: "New entry — dealer incentives beginning to appear",
  },
  {
    id: "mercedes-eqb-2024",
    brand: "Mercedes-Benz",
    model: "EQB",
    year: 2024,
    bodyType: "suv",
    msrp: 52750,
    bestNewPrice: 46200,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/mercedes-benz/eqb",
    bestUsedPrice: 38500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/mercedes-benz/eqb",
    bestUsedYear: 2023,
    bestUsedMileage: "14k mi",
    range: 245,
    zeroToSixty: "5.6s",
    chargingSpeed: "120 mi",
    trueValueScore: 68,
    efficiency: 2.9,
    cargoSpace: "62 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 78, annual: 936, fiveYear: 4680 },
    ownershipCost: {
      electricity5yr: 2850,
      insurance5yr: 10500,
      maintenance5yr: 5200,
      totalCost5yr: 66300,
      resalePercent: 38,
      resaleValue: 20045,
      netCost: 46255,
    },
    batteryDetails: {
      capacity: "70.5 kWh",
      realWorldRange: "220-240 mi",
      coldWeatherRange: "170-200 mi",
      degradationNote: "Compact 3-row EV; conservative charging speeds — ~5% loss at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/mercedes-benz/eqb" },
      { name: "CarMax", url: "https://www.carmax.com/cars/mercedes-benz/eqb" },
      { name: "Carvana", url: "https://www.carvana.com/cars/mercedes-benz-eqb" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/mercedes_benz-eqb/" },
    ],
    trendPercent: -6.8,
    trendNote: "Mercedes EV discounts accelerating — rare 3-row option",
  },
  {
    id: "kia-niro-ev-2024",
    brand: "Kia",
    model: "Niro EV",
    year: 2024,
    bodyType: "suv",
    msrp: 39600,
    bestNewPrice: 35200,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/kia/niro-ev",
    bestUsedPrice: 29500,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/kia-niro-ev",
    bestUsedYear: 2023,
    bestUsedMileage: "16k mi",
    range: 253,
    zeroToSixty: "6.2s",
    chargingSpeed: "110 mi",
    trueValueScore: 82,
    efficiency: 3.4,
    cargoSpace: "63 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 90, annual: 1080, fiveYear: 5400 },
    ownershipCost: {
      electricity5yr: 2500,
      insurance5yr: 7800,
      maintenance5yr: 4000,
      totalCost5yr: 49100,
      resalePercent: 44,
      resaleValue: 17424,
      netCost: 31676,
    },
    batteryDetails: {
      capacity: "64.8 kWh",
      realWorldRange: "230-250 mi",
      coldWeatherRange: "180-205 mi",
      degradationNote: "Proven battery chemistry from Kia/Hyundai — ~5% loss at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/kia/niro-ev" },
      { name: "Carvana", url: "https://www.carvana.com/cars/kia-niro-ev" },
      { name: "CarMax", url: "https://www.carmax.com/cars/kia/niro-ev" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/kia-niro_ev/" },
    ],
    trendPercent: -4.8,
    trendNote: "Practical and affordable — strong dealer discounts",
  },

  // === NEW TRUCKS ===
  {
    id: "gmc-sierra-ev-2024",
    brand: "GMC",
    model: "Sierra EV",
    year: 2024,
    bodyType: "truck",
    msrp: 99995,
    bestNewPrice: 92500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/gmc/sierra-ev",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 400,
    zeroToSixty: "4.5s",
    chargingSpeed: "190 mi",
    trueValueScore: 62,
    efficiency: 1.9,
    cargoSpace: "89 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 115, annual: 1380, fiveYear: 6900 },
    ownershipCost: {
      electricity5yr: 4500,
      insurance5yr: 13500,
      maintenance5yr: 5500,
      totalCost5yr: 119495,
      resalePercent: 42,
      resaleValue: 41998,
      netCost: 77497,
    },
    batteryDetails: {
      capacity: "200 kWh (Ultium)",
      realWorldRange: "370-395 mi",
      coldWeatherRange: "290-330 mi",
      degradationNote: "Massive Ultium battery; CrabWalk & MultiPro tailgate — premium EV truck",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/gmc/sierra-ev" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/gmc-sierra_ev/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-GMC-Sierra-EV" },
    ],
    trendPercent: -3.2,
    trendNote: "Denali Edition 1 prices stabilizing; lower trims incoming",
  },

  // === NEW VAN ===
  {
    id: "vw-id-buzz-2024",
    brand: "Volkswagen",
    model: "ID.Buzz",
    year: 2024,
    bodyType: "van",
    msrp: 59995,
    bestNewPrice: 55500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/volkswagen/id-buzz",
    bestUsedPrice: 49800,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/volkswagen/id-buzz",
    bestUsedYear: 2024,
    bestUsedMileage: "5k mi",
    range: 234,
    zeroToSixty: "6.6s",
    chargingSpeed: "120 mi",
    trueValueScore: 71,
    efficiency: 2.4,
    cargoSpace: "117 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 72, annual: 864, fiveYear: 4320 },
    ownershipCost: {
      electricity5yr: 3200,
      insurance5yr: 9800,
      maintenance5yr: 4800,
      totalCost5yr: 73795,
      resalePercent: 46,
      resaleValue: 27598,
      netCost: 46197,
    },
    batteryDetails: {
      capacity: "91 kWh",
      realWorldRange: "210-230 mi",
      coldWeatherRange: "165-190 mi",
      degradationNote: "MEB platform; retro-styled van with solid VW battery reliability — ~5% at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/volkswagen/id-buzz" },
      { name: "CarMax", url: "https://www.carmax.com/cars/volkswagen/id-buzz" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/volkswagen-id_buzz/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Volkswagen-ID.Buzz" },
    ],
    trendPercent: -3.0,
    trendNote: "Iconic design holding value — modest dealer discounts",
  },

  // === NEW HATCHBACKS ===
  {
    id: "mini-cooper-electric-2024",
    brand: "Mini",
    model: "Cooper Electric",
    year: 2024,
    bodyType: "hatchback",
    msrp: 34900,
    bestNewPrice: 30500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/mini/cooper-electric",
    bestUsedPrice: 25800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/mini-cooper-electric",
    bestUsedYear: 2023,
    bestUsedMileage: "10k mi",
    range: 114,
    zeroToSixty: "6.9s",
    chargingSpeed: "60 mi",
    trueValueScore: 63,
    efficiency: 3.2,
    cargoSpace: "34 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 70, annual: 840, fiveYear: 4200 },
    ownershipCost: {
      electricity5yr: 2000,
      insurance5yr: 8200,
      maintenance5yr: 4200,
      totalCost5yr: 45300,
      resalePercent: 38,
      resaleValue: 13262,
      netCost: 32038,
    },
    batteryDetails: {
      capacity: "32.6 kWh",
      realWorldRange: "100-110 mi",
      coldWeatherRange: "75-90 mi",
      degradationNote: "Small battery limits range but charges quickly; best for city driving — ~4% at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/mini/cooper-electric" },
      { name: "Carvana", url: "https://www.carvana.com/cars/mini-cooper-electric" },
      { name: "CarMax", url: "https://www.carmax.com/cars/mini/cooper-electric" },
    ],
    trendPercent: -7.0,
    trendNote: "Limited range hurting resale — great city car deals",
  },
  {
    id: "fiat-500e-2024",
    brand: "Fiat",
    model: "500e",
    year: 2024,
    bodyType: "hatchback",
    msrp: 32500,
    bestNewPrice: 28500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/fiat/500e",
    bestUsedPrice: 24200,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/fiat-500e",
    bestUsedYear: 2024,
    bestUsedMileage: "6k mi",
    range: 149,
    zeroToSixty: "7.0s",
    chargingSpeed: "70 mi",
    trueValueScore: 65,
    efficiency: 3.3,
    cargoSpace: "14 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 72, annual: 864, fiveYear: 4320 },
    ownershipCost: {
      electricity5yr: 2100,
      insurance5yr: 7500,
      maintenance5yr: 3800,
      totalCost5yr: 41900,
      resalePercent: 36,
      resaleValue: 11700,
      netCost: 30200,
    },
    batteryDetails: {
      capacity: "42 kWh",
      realWorldRange: "130-145 mi",
      coldWeatherRange: "100-120 mi",
      degradationNote: "Stylish city EV; small battery prioritizes urban use — ~5% at 50k mi",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/fiat/500e" },
      { name: "Carvana", url: "https://www.carvana.com/cars/fiat-500e" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/fiat-500e/" },
    ],
    trendPercent: -5.5,
    trendNote: "Affordable urban EV — incentives making it even cheaper",
  },
  {
    id: "chevy-bolt-ev-2027",
    brand: "Chevrolet",
    model: "Bolt EV (2027)",
    year: 2027,
    bodyType: "hatchback",
    msrp: 27495,
    bestNewPrice: null,
    bestNewPlatform: null,
    bestNewUrl: "",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 305,
    zeroToSixty: "5.5s",
    chargingSpeed: "140 mi",
    trueValueScore: 92,
    efficiency: 3.8,
    cargoSpace: "57 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 98, annual: 1176, fiveYear: 5880 },
    ownershipCost: {
      electricity5yr: 2300,
      insurance5yr: 7000,
      maintenance5yr: 3800,
      totalCost5yr: 38095,
      resalePercent: 45,
      resaleValue: 12373,
      netCost: 25722,
    },
    batteryDetails: {
      capacity: "75 kWh (Ultium)",
      realWorldRange: "280-300 mi",
      coldWeatherRange: "215-245 mi",
      degradationNote: "Next-gen Ultium platform; expected class-leading value and efficiency",
    },
    platforms: [
      { name: "Chevrolet.com", url: "https://www.chevrolet.com/electric/bolt-ev" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/chevrolet/bolt-ev" },
    ],
    trendPercent: 0.0,
    trendNote: "Not yet available — estimated pricing based on GM announcements",
  },
];

// Gas car comparison data for savings calculator
export const GAS_CARS = [
  { name: "Honda Civic", mpg: 33 },
  { name: "Toyota Camry", mpg: 32 },
  { name: "Toyota RAV4", mpg: 30 },
  { name: "Honda CR-V", mpg: 30 },
  { name: "Ford F-150", mpg: 24 },
  { name: "Chevy Silverado", mpg: 23 },
  { name: "Toyota Highlander", mpg: 25 },
  { name: "BMW X5", mpg: 25 },
];

// Market pulse data for dashboard
export const MARKET_PULSE = [
  { model: "Tesla Model Y", percent: -4.2, note: "Prices dropping — great time to buy" },
  { model: "Tesla Model 3", percent: -3.8, note: "Used prices softening significantly" },
  { model: "Chevy Equinox EV", percent: -6.1, note: "Aggressive dealer discounts" },
  { model: "Ford Mustang Mach-E", percent: -5.5, note: "Steep markdowns on 2024 models" },
  { model: "Hyundai Ioniq 5", percent: -7.2, note: "Best deals in the EV market right now" },
  { model: "Kia EV6", percent: -4.9, note: "Competitive pricing across dealers" },
  { model: "BMW iX", percent: -8.3, note: "Luxury EVs seeing biggest drops" },
  { model: "Rivian R1S", percent: 2.1, note: "Limited supply keeping prices firm" },
  { model: "Toyota bZ4X", percent: -9.5, note: "Deep discounts to move inventory" },
  { model: "Nissan Ariya", percent: -6.8, note: "Undervalued — strong specs for the price" },
  { model: "Hyundai Ioniq 6", percent: -5.8, note: "Sleek sedan with incredible efficiency" },
  { model: "Honda Prologue", percent: -4.5, note: "Honda's first EV gaining dealer momentum" },
];

// Unique brands for filter
export const EV_BRANDS = [...new Set(EV_DEALS.map((d) => d.brand))].sort();
