// EV Best Price Finder — Data File
// Updated: March 2026
// Update this file monthly with latest pricing from Carvana, CarMax, AutoTrader, etc.

export interface EvDeal {
  id: string;
  brand: string;
  model: string;
  year: number;
  bodyType: "sedan" | "suv" | "truck" | "hatchback";
  msrp: number;
  bestNewPrice: number | null;
  bestNewPlatform: string | null;
  bestNewUrl: string;
  bestUsedPrice: number | null;
  bestUsedPlatform: string | null;
  bestUsedUrl: string;
  bestUsedYear: number | null;
  bestUsedMileage: string | null;
  range: number;
  zeroToSixty: string;
  chargingSpeed: string; // miles added per 15 min fast charge
  trueValueScore: number;
  efficiency: number; // mi/kWh
  cargoSpace: string;
  warranty: string;
  fuelSavings: { monthly: number; annual: number; fiveYear: number };
  ownershipCost: {
    electricity5yr: number;
    insurance5yr: number;
    maintenance5yr: number;
    totalCost5yr: number;
    resalePercent: number;
    resaleValue: number;
    netCost: number;
  };
  batteryDetails: {
    capacity: string;
    realWorldRange: string;
    coldWeatherRange: string;
    degradationNote: string;
  };
  platforms: { name: string; url: string }[];
  trendPercent: number; // negative = price drop (good for buyers)
  trendNote: string;
  featured?: boolean;
  featuredNote?: string;
  discontinued?: boolean;
}

export const EV_DEALS: EvDeal[] = [
  // === SEDANS ===
  {
    id: "tesla-model-3-2024",
    brand: "Tesla",
    model: "Model 3",
    year: 2024,
    bodyType: "sedan",
    msrp: 38990,
    bestNewPrice: 36500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/tesla/model-3",
    bestUsedPrice: 29800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/tesla-model-3",
    bestUsedYear: 2023,
    bestUsedMileage: "18k mi",
    range: 272,
    zeroToSixty: "5.8s",
    chargingSpeed: "170 mi",
    trueValueScore: 82,
    efficiency: 3.8,
    cargoSpace: "23 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 92, annual: 1104, fiveYear: 5520 },
    ownershipCost: {
      electricity5yr: 2526,
      insurance5yr: 9000,
      maintenance5yr: 4500,
      totalCost5yr: 52526,
      resalePercent: 52,
      resaleValue: 18980,
      netCost: 33546,
    },
    batteryDetails: {
      capacity: "60 kWh",
      realWorldRange: "245-265 mi",
      coldWeatherRange: "190-210 mi",
      degradationNote: "~5% loss at 50k mi; Tesla batteries hold up well",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/tesla/model-3" },
      { name: "Carvana", url: "https://www.carvana.com/cars/tesla-model-3" },
      { name: "CarMax", url: "https://www.carmax.com/cars/tesla/model-3" },
      { name: "Tesla.com", url: "https://www.tesla.com/model3" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/tesla-model_3/" },
    ],
    trendPercent: -3.8,
    trendNote: "Used prices softening significantly",
  },
  {
    id: "tesla-model-s-2024",
    brand: "Tesla",
    model: "Model S",
    year: 2024,
    bodyType: "sedan",
    msrp: 74990,
    bestNewPrice: 71000,
    bestNewPlatform: "Tesla.com",
    bestNewUrl: "https://www.tesla.com/models",
    bestUsedPrice: 58500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/tesla/model-s",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 405,
    zeroToSixty: "3.1s",
    chargingSpeed: "200 mi",
    trueValueScore: 68,
    efficiency: 3.2,
    cargoSpace: "28 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/150k battery",
    fuelSavings: { monthly: 87, annual: 1044, fiveYear: 5220 },
    ownershipCost: {
      electricity5yr: 3000,
      insurance5yr: 12000,
      maintenance5yr: 4500,
      totalCost5yr: 90500,
      resalePercent: 48,
      resaleValue: 34080,
      netCost: 56420,
    },
    batteryDetails: {
      capacity: "100 kWh",
      realWorldRange: "370-395 mi",
      coldWeatherRange: "290-320 mi",
      degradationNote: "~4% loss at 50k mi; flagship battery quality",
    },
    platforms: [
      { name: "Tesla.com", url: "https://www.tesla.com/models" },
      { name: "CarMax", url: "https://www.carmax.com/cars/tesla/model-s" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/tesla/model-s" },
      { name: "Carvana", url: "https://www.carvana.com/cars/tesla-model-s" },
    ],
    trendPercent: -4.0,
    trendNote: "Luxury sedan market softening",
  },
  {
    id: "bmw-i4-2024",
    brand: "BMW",
    model: "i4 eDrive40",
    year: 2024,
    bodyType: "sedan",
    msrp: 52200,
    bestNewPrice: 46800,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/bmw/i4",
    bestUsedPrice: 38900,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/bmw-i4",
    bestUsedYear: 2023,
    bestUsedMileage: "12k mi",
    range: 301,
    zeroToSixty: "5.5s",
    chargingSpeed: "108 mi",
    trueValueScore: 78,
    efficiency: 3.5,
    cargoSpace: "18 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 89, annual: 1068, fiveYear: 5340 },
    ownershipCost: {
      electricity5yr: 2743,
      insurance5yr: 10500,
      maintenance5yr: 5000,
      totalCost5yr: 65043,
      resalePercent: 45,
      resaleValue: 21060,
      netCost: 43983,
    },
    batteryDetails: {
      capacity: "83.9 kWh",
      realWorldRange: "270-290 mi",
      coldWeatherRange: "210-240 mi",
      degradationNote: "~6% at 50k mi; solid BMW battery management",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/bmw/i4" },
      { name: "Carvana", url: "https://www.carvana.com/cars/bmw-i4" },
      { name: "CarMax", url: "https://www.carmax.com/cars/bmw/i4" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/bmw-i4/" },
    ],
    trendPercent: -5.2,
    trendNote: "Dealers offering strong incentives",
  },
  {
    id: "polestar-2-2024",
    brand: "Polestar",
    model: "Polestar 2",
    year: 2024,
    bodyType: "sedan",
    msrp: 44900,
    bestNewPrice: 38500,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/polestar-2/",
    bestUsedPrice: 29200,
    bestUsedPlatform: "CarGurus",
    bestUsedUrl: "https://www.cargurus.com/Cars/l-Used-Polestar-2",
    bestUsedYear: 2023,
    bestUsedMileage: "20k mi",
    range: 270,
    zeroToSixty: "6.2s",
    chargingSpeed: "100 mi",
    trueValueScore: 80,
    efficiency: 3.4,
    cargoSpace: "14 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 90, annual: 1080, fiveYear: 5400 },
    ownershipCost: {
      electricity5yr: 2824,
      insurance5yr: 8500,
      maintenance5yr: 4500,
      totalCost5yr: 54324,
      resalePercent: 42,
      resaleValue: 16170,
      netCost: 38154,
    },
    batteryDetails: {
      capacity: "78 kWh",
      realWorldRange: "240-260 mi",
      coldWeatherRange: "185-210 mi",
      degradationNote: "~6% at 50k mi; Volvo/Geely battery tech",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/polestar-2/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Polestar-2" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/polestar/2" },
    ],
    trendPercent: -6.0,
    trendNote: "Steep depreciation creates great used deals",
  },
  {
    id: "lucid-air-pure-2024",
    brand: "Lucid",
    model: "Air Pure",
    year: 2024,
    bodyType: "sedan",
    msrp: 69900,
    bestNewPrice: 63000,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/lucid/air",
    bestUsedPrice: 49500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/lucid/air",
    bestUsedYear: 2023,
    bestUsedMileage: "10k mi",
    range: 410,
    zeroToSixty: "3.8s",
    chargingSpeed: "200 mi",
    trueValueScore: 72,
    efficiency: 4.6,
    cargoSpace: "32 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 95, annual: 1140, fiveYear: 5700 },
    ownershipCost: {
      electricity5yr: 2087,
      insurance5yr: 11000,
      maintenance5yr: 4500,
      totalCost5yr: 81587,
      resalePercent: 40,
      resaleValue: 25200,
      netCost: 56387,
    },
    batteryDetails: {
      capacity: "92 kWh",
      realWorldRange: "380-400 mi",
      coldWeatherRange: "290-330 mi",
      degradationNote: "~5% at 50k mi; Lucid's industry-leading efficiency",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/lucid/air" },
      { name: "CarMax", url: "https://www.carmax.com/cars/lucid/air" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/lucid-air/" },
    ],
    trendPercent: -7.5,
    trendNote: "Best luxury EV value on the used market",
  },
  {
    id: "nissan-leaf-2024",
    brand: "Nissan",
    model: "Leaf S",
    year: 2024,
    bodyType: "sedan",
    msrp: 28140,
    bestNewPrice: 24500,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/nissan-leaf/",
    bestUsedPrice: 17800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/nissan-leaf",
    bestUsedYear: 2023,
    bestUsedMileage: "22k mi",
    range: 149,
    zeroToSixty: "7.4s",
    chargingSpeed: "50 mi",
    trueValueScore: 75,
    efficiency: 3.3,
    cargoSpace: "24 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 91, annual: 1092, fiveYear: 5460 },
    ownershipCost: {
      electricity5yr: 2909,
      insurance5yr: 7000,
      maintenance5yr: 4000,
      totalCost5yr: 38409,
      resalePercent: 35,
      resaleValue: 8575,
      netCost: 29834,
    },
    batteryDetails: {
      capacity: "40 kWh",
      realWorldRange: "125-140 mi",
      coldWeatherRange: "100-115 mi",
      degradationNote: "~8% at 50k mi; air-cooled battery degrades faster than liquid-cooled",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/nissan-leaf/" },
      { name: "Carvana", url: "https://www.carvana.com/cars/nissan-leaf" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Nissan-LEAF" },
    ],
    trendPercent: -5.0,
    trendNote: "Cheapest EV entry point on the market",
  },

  // === SUVs ===
  {
    id: "tesla-model-y-2024",
    brand: "Tesla",
    model: "Model Y",
    year: 2024,
    bodyType: "suv",
    msrp: 44990,
    bestNewPrice: 42000,
    bestNewPlatform: "Tesla.com",
    bestNewUrl: "https://www.tesla.com/modely",
    bestUsedPrice: 33500,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/tesla-model-y",
    bestUsedYear: 2023,
    bestUsedMileage: "20k mi",
    range: 310,
    zeroToSixty: "5.0s",
    chargingSpeed: "162 mi",
    trueValueScore: 85,
    efficiency: 3.5,
    cargoSpace: "68 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 95, annual: 1140, fiveYear: 5700 },
    ownershipCost: {
      electricity5yr: 2743,
      insurance5yr: 9500,
      maintenance5yr: 4500,
      totalCost5yr: 58743,
      resalePercent: 55,
      resaleValue: 23100,
      netCost: 35643,
    },
    batteryDetails: {
      capacity: "75 kWh",
      realWorldRange: "280-300 mi",
      coldWeatherRange: "215-245 mi",
      degradationNote: "~5% at 50k mi; best-selling EV for a reason",
    },
    platforms: [
      { name: "Tesla.com", url: "https://www.tesla.com/modely" },
      { name: "Carvana", url: "https://www.carvana.com/cars/tesla-model-y" },
      { name: "CarMax", url: "https://www.carmax.com/cars/tesla/model-y" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/tesla/model-y" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/tesla-model_y/" },
    ],
    trendPercent: -4.2,
    trendNote: "Prices dropping — great time to buy",
  },
  {
    id: "chevy-equinox-ev-2024",
    brand: "Chevrolet",
    model: "Equinox EV LT",
    year: 2024,
    bodyType: "suv",
    msrp: 33900,
    bestNewPrice: 29200,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/chevrolet/equinox-ev",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 319,
    zeroToSixty: "6.0s",
    chargingSpeed: "150 mi",
    trueValueScore: 94,
    efficiency: 3.6,
    cargoSpace: "57 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 96, annual: 1152, fiveYear: 5760 },
    ownershipCost: {
      electricity5yr: 2667,
      insurance5yr: 8000,
      maintenance5yr: 4500,
      totalCost5yr: 44367,
      resalePercent: 50,
      resaleValue: 14600,
      netCost: 29767,
    },
    batteryDetails: {
      capacity: "85 kWh",
      realWorldRange: "290-310 mi",
      coldWeatherRange: "220-250 mi",
      degradationNote: "Too new for real-world data; Ultium platform promising",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/chevrolet/equinox-ev" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/chevrolet-equinox_ev/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Chevrolet-Equinox-EV" },
    ],
    trendPercent: -6.1,
    trendNote: "Aggressive dealer discounts",
    featured: true,
    featuredNote: "Most affordable long-range EV on the market. $29k for 319 miles of range is unmatched.",
  },
  {
    id: "ford-mach-e-2024",
    brand: "Ford",
    model: "Mustang Mach-E",
    year: 2024,
    bodyType: "suv",
    msrp: 42995,
    bestNewPrice: 37500,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/ford-mustang_mach-e/",
    bestUsedPrice: 28900,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/ford/mustang-mach-e",
    bestUsedYear: 2023,
    bestUsedMileage: "18k mi",
    range: 312,
    zeroToSixty: "5.1s",
    chargingSpeed: "120 mi",
    trueValueScore: 83,
    efficiency: 3.4,
    cargoSpace: "60 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 93, annual: 1116, fiveYear: 5580 },
    ownershipCost: {
      electricity5yr: 2824,
      insurance5yr: 9000,
      maintenance5yr: 4500,
      totalCost5yr: 53824,
      resalePercent: 48,
      resaleValue: 18000,
      netCost: 35824,
    },
    batteryDetails: {
      capacity: "91 kWh",
      realWorldRange: "280-300 mi",
      coldWeatherRange: "215-245 mi",
      degradationNote: "~5% at 50k mi; Ford improved battery in 2024",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/ford-mustang_mach-e/" },
      { name: "CarMax", url: "https://www.carmax.com/cars/ford/mustang-mach-e" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/ford/mustang-mach-e" },
      { name: "Carvana", url: "https://www.carvana.com/cars/ford-mustang-mach-e" },
    ],
    trendPercent: -5.5,
    trendNote: "Steep markdowns on 2024 models",
  },
  {
    id: "hyundai-ioniq-5-2024",
    brand: "Hyundai",
    model: "Ioniq 5",
    year: 2024,
    bodyType: "suv",
    msrp: 41800,
    bestNewPrice: 35200,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/hyundai/ioniq-5",
    bestUsedPrice: 27500,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/hyundai-ioniq-5",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 303,
    zeroToSixty: "5.2s",
    chargingSpeed: "180 mi",
    trueValueScore: 88,
    efficiency: 3.5,
    cargoSpace: "60 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 95, annual: 1140, fiveYear: 5700 },
    ownershipCost: {
      electricity5yr: 2743,
      insurance5yr: 8500,
      maintenance5yr: 4500,
      totalCost5yr: 50943,
      resalePercent: 50,
      resaleValue: 17600,
      netCost: 33343,
    },
    batteryDetails: {
      capacity: "77.4 kWh",
      realWorldRange: "270-295 mi",
      coldWeatherRange: "210-240 mi",
      degradationNote: "~4% at 50k mi; 800V architecture charges incredibly fast",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/hyundai/ioniq-5" },
      { name: "Carvana", url: "https://www.carvana.com/cars/hyundai-ioniq-5" },
      { name: "CarMax", url: "https://www.carmax.com/cars/hyundai/ioniq-5" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/hyundai-ioniq_5/" },
    ],
    trendPercent: -7.2,
    trendNote: "Best deals in the EV market right now",
  },
  {
    id: "kia-ev6-2024",
    brand: "Kia",
    model: "EV6 Wind",
    year: 2024,
    bodyType: "suv",
    msrp: 42600,
    bestNewPrice: 37800,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/kia-ev6/",
    bestUsedPrice: 29200,
    bestUsedPlatform: "CarGurus",
    bestUsedUrl: "https://www.cargurus.com/Cars/l-Used-Kia-EV6",
    bestUsedYear: 2023,
    bestUsedMileage: "16k mi",
    range: 310,
    zeroToSixty: "5.1s",
    chargingSpeed: "180 mi",
    trueValueScore: 86,
    efficiency: 3.5,
    cargoSpace: "50 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 95, annual: 1140, fiveYear: 5700 },
    ownershipCost: {
      electricity5yr: 2743,
      insurance5yr: 8500,
      maintenance5yr: 4500,
      totalCost5yr: 53543,
      resalePercent: 48,
      resaleValue: 18144,
      netCost: 35399,
    },
    batteryDetails: {
      capacity: "77.4 kWh",
      realWorldRange: "275-300 mi",
      coldWeatherRange: "210-240 mi",
      degradationNote: "~4% at 50k mi; same 800V platform as Ioniq 5",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/kia-ev6/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Kia-EV6" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/kia/ev6" },
      { name: "Carvana", url: "https://www.carvana.com/cars/kia-ev6" },
    ],
    trendPercent: -4.9,
    trendNote: "Competitive pricing across dealers",
  },
  {
    id: "vw-id4-2024",
    brand: "Volkswagen",
    model: "ID.4",
    year: 2024,
    bodyType: "suv",
    msrp: 39735,
    bestNewPrice: 34500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/volkswagen/id.4",
    bestUsedPrice: 25800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/volkswagen-id.4",
    bestUsedYear: 2023,
    bestUsedMileage: "20k mi",
    range: 275,
    zeroToSixty: "5.7s",
    chargingSpeed: "100 mi",
    trueValueScore: 79,
    efficiency: 3.3,
    cargoSpace: "64 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 91, annual: 1092, fiveYear: 5460 },
    ownershipCost: {
      electricity5yr: 2909,
      insurance5yr: 8000,
      maintenance5yr: 4500,
      totalCost5yr: 49909,
      resalePercent: 42,
      resaleValue: 14490,
      netCost: 35419,
    },
    batteryDetails: {
      capacity: "82 kWh",
      realWorldRange: "250-270 mi",
      coldWeatherRange: "190-220 mi",
      degradationNote: "~6% at 50k mi; VW's MEB platform is proven",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/volkswagen/id.4" },
      { name: "Carvana", url: "https://www.carvana.com/cars/volkswagen-id.4" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/volkswagen-id.4/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Volkswagen-ID.4" },
    ],
    trendPercent: -5.8,
    trendNote: "Strong incentives and dealer discounts",
  },
  {
    id: "bmw-ix-2024",
    brand: "BMW",
    model: "iX xDrive50",
    year: 2024,
    bodyType: "suv",
    msrp: 87100,
    bestNewPrice: 78000,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/bmw/ix",
    bestUsedPrice: 59500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/bmw/ix",
    bestUsedYear: 2023,
    bestUsedMileage: "12k mi",
    range: 324,
    zeroToSixty: "4.4s",
    chargingSpeed: "130 mi",
    trueValueScore: 70,
    efficiency: 3.1,
    cargoSpace: "77 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 88, annual: 1056, fiveYear: 5280 },
    ownershipCost: {
      electricity5yr: 3097,
      insurance5yr: 13000,
      maintenance5yr: 5500,
      totalCost5yr: 99597,
      resalePercent: 42,
      resaleValue: 32760,
      netCost: 66837,
    },
    batteryDetails: {
      capacity: "111.5 kWh",
      realWorldRange: "290-315 mi",
      coldWeatherRange: "225-260 mi",
      degradationNote: "~5% at 50k mi; BMW's 5th gen eDrive tech",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/bmw/ix" },
      { name: "CarMax", url: "https://www.carmax.com/cars/bmw/ix" },
      { name: "Carvana", url: "https://www.carvana.com/cars/bmw-ix" },
    ],
    trendPercent: -8.3,
    trendNote: "Luxury EVs seeing biggest drops",
  },
  {
    id: "mercedes-eqs-suv-2024",
    brand: "Mercedes",
    model: "EQS SUV",
    year: 2024,
    bodyType: "suv",
    msrp: 104400,
    bestNewPrice: 94000,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/mercedes_benz-eqs_suv/",
    bestUsedPrice: 72000,
    bestUsedPlatform: "AutoTrader",
    bestUsedUrl: "https://www.autotrader.com/cars-for-sale/mercedes-benz/eqs",
    bestUsedYear: 2023,
    bestUsedMileage: "10k mi",
    range: 305,
    zeroToSixty: "4.5s",
    chargingSpeed: "120 mi",
    trueValueScore: 65,
    efficiency: 2.9,
    cargoSpace: "74 cu ft",
    warranty: "4yr/50k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 85, annual: 1020, fiveYear: 5100 },
    ownershipCost: {
      electricity5yr: 3310,
      insurance5yr: 15000,
      maintenance5yr: 6000,
      totalCost5yr: 118310,
      resalePercent: 40,
      resaleValue: 37600,
      netCost: 80710,
    },
    batteryDetails: {
      capacity: "108.4 kWh",
      realWorldRange: "270-295 mi",
      coldWeatherRange: "210-245 mi",
      degradationNote: "~5% at 50k mi; premium battery management system",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/mercedes_benz-eqs_suv/" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/mercedes-benz/eqs" },
      { name: "CarMax", url: "https://www.carmax.com/cars/mercedes-benz/eqs" },
    ],
    trendPercent: -9.0,
    trendNote: "Massive depreciation on luxury EVs",
  },
  {
    id: "toyota-bz4x-2024",
    brand: "Toyota",
    model: "bZ4X",
    year: 2024,
    bodyType: "suv",
    msrp: 42000,
    bestNewPrice: 33500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/toyota/bz4x",
    bestUsedPrice: 24800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/toyota-bz4x",
    bestUsedYear: 2023,
    bestUsedMileage: "18k mi",
    range: 252,
    zeroToSixty: "6.6s",
    chargingSpeed: "80 mi",
    trueValueScore: 81,
    efficiency: 3.1,
    cargoSpace: "60 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 10yr/150k battery",
    fuelSavings: { monthly: 88, annual: 1056, fiveYear: 5280 },
    ownershipCost: {
      electricity5yr: 3097,
      insurance5yr: 8500,
      maintenance5yr: 4500,
      totalCost5yr: 49597,
      resalePercent: 48,
      resaleValue: 16080,
      netCost: 33517,
    },
    batteryDetails: {
      capacity: "71.4 kWh",
      realWorldRange: "225-245 mi",
      coldWeatherRange: "175-205 mi",
      degradationNote: "Toyota's 10yr/150k warranty shows battery confidence",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/toyota/bz4x" },
      { name: "Carvana", url: "https://www.carvana.com/cars/toyota-bz4x" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/toyota-bz4x/" },
    ],
    trendPercent: -9.5,
    trendNote: "Deep discounts to move inventory",
  },
  {
    id: "nissan-ariya-2024",
    brand: "Nissan",
    model: "Ariya",
    year: 2024,
    bodyType: "suv",
    msrp: 39590,
    bestNewPrice: 33200,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/nissan-ariya/",
    bestUsedPrice: 26500,
    bestUsedPlatform: "CarGurus",
    bestUsedUrl: "https://www.cargurus.com/Cars/l-Used-Nissan-Ariya",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 304,
    zeroToSixty: "5.9s",
    chargingSpeed: "100 mi",
    trueValueScore: 84,
    efficiency: 3.4,
    cargoSpace: "59 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 93, annual: 1116, fiveYear: 5580 },
    ownershipCost: {
      electricity5yr: 2824,
      insurance5yr: 8000,
      maintenance5yr: 4500,
      totalCost5yr: 48524,
      resalePercent: 42,
      resaleValue: 13950,
      netCost: 34574,
    },
    batteryDetails: {
      capacity: "87 kWh",
      realWorldRange: "270-295 mi",
      coldWeatherRange: "210-240 mi",
      degradationNote: "~5% at 50k mi; liquid-cooled, much better than Leaf",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/nissan-ariya/" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Nissan-Ariya" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/nissan/ariya" },
    ],
    trendPercent: -6.8,
    trendNote: "Undervalued — strong specs for the price",
  },
  {
    id: "chevy-blazer-ev-2024",
    brand: "Chevrolet",
    model: "Blazer EV",
    year: 2024,
    bodyType: "suv",
    msrp: 45595,
    bestNewPrice: 38000,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/chevrolet/blazer-ev",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 279,
    zeroToSixty: "5.6s",
    chargingSpeed: "120 mi",
    trueValueScore: 76,
    efficiency: 3.2,
    cargoSpace: "55 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 90, annual: 1080, fiveYear: 5400 },
    ownershipCost: {
      electricity5yr: 3000,
      insurance5yr: 9000,
      maintenance5yr: 4500,
      totalCost5yr: 54500,
      resalePercent: 45,
      resaleValue: 17100,
      netCost: 37400,
    },
    batteryDetails: {
      capacity: "85 kWh",
      realWorldRange: "250-270 mi",
      coldWeatherRange: "195-225 mi",
      degradationNote: "Too new for data; Ultium platform shared with Equinox EV",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/chevrolet/blazer-ev" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/chevrolet-blazer_ev/" },
    ],
    trendPercent: -4.5,
    trendNote: "Post-recall prices stabilizing with discounts",
  },
  {
    id: "rivian-r1s-2024",
    brand: "Rivian",
    model: "R1S",
    year: 2024,
    bodyType: "suv",
    msrp: 75900,
    bestNewPrice: 75900,
    bestNewPlatform: "Rivian.com",
    bestNewUrl: "https://rivian.com/r1s",
    bestUsedPrice: 62000,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/rivian/r1s",
    bestUsedYear: 2023,
    bestUsedMileage: "12k mi",
    range: 321,
    zeroToSixty: "3.0s",
    chargingSpeed: "140 mi",
    trueValueScore: 71,
    efficiency: 2.8,
    cargoSpace: "104 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 8yr/175k battery",
    fuelSavings: { monthly: 82, annual: 984, fiveYear: 4920 },
    ownershipCost: {
      electricity5yr: 3429,
      insurance5yr: 11500,
      maintenance5yr: 4500,
      totalCost5yr: 95329,
      resalePercent: 55,
      resaleValue: 41745,
      netCost: 53584,
    },
    batteryDetails: {
      capacity: "135 kWh",
      realWorldRange: "285-310 mi",
      coldWeatherRange: "225-260 mi",
      degradationNote: "~4% at 50k mi; massive battery pack with great longevity",
    },
    platforms: [
      { name: "Rivian.com", url: "https://rivian.com/r1s" },
      { name: "CarMax", url: "https://www.carmax.com/cars/rivian/r1s" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/rivian/r1s" },
    ],
    trendPercent: 2.1,
    trendNote: "Limited supply keeping prices firm",
  },
  {
    id: "kia-ev9-2024",
    brand: "Kia",
    model: "EV9",
    year: 2024,
    bodyType: "suv",
    msrp: 54900,
    bestNewPrice: 49500,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/kia/ev9",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 304,
    zeroToSixty: "5.0s",
    chargingSpeed: "180 mi",
    trueValueScore: 77,
    efficiency: 3.0,
    cargoSpace: "82 cu ft",
    warranty: "5yr/60k bumper-to-bumper, 10yr/100k battery",
    fuelSavings: { monthly: 87, annual: 1044, fiveYear: 5220 },
    ownershipCost: {
      electricity5yr: 3200,
      insurance5yr: 9500,
      maintenance5yr: 4500,
      totalCost5yr: 66700,
      resalePercent: 50,
      resaleValue: 24750,
      netCost: 41950,
    },
    batteryDetails: {
      capacity: "99.8 kWh",
      realWorldRange: "270-295 mi",
      coldWeatherRange: "210-245 mi",
      degradationNote: "Too new for data; 800V architecture with 10yr warranty",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/kia/ev9" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/kia-ev9/" },
    ],
    trendPercent: -3.5,
    trendNote: "Three-row EV with growing availability",
  },
  {
    id: "subaru-solterra-2024",
    brand: "Subaru",
    model: "Solterra",
    year: 2024,
    bodyType: "suv",
    msrp: 44995,
    bestNewPrice: 36000,
    bestNewPlatform: "Cars.com",
    bestNewUrl: "https://www.cars.com/shopping/subaru-solterra/",
    bestUsedPrice: 26500,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/subaru-solterra",
    bestUsedYear: 2023,
    bestUsedMileage: "20k mi",
    range: 228,
    zeroToSixty: "6.5s",
    chargingSpeed: "80 mi",
    trueValueScore: 74,
    efficiency: 3.0,
    cargoSpace: "53 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 87, annual: 1044, fiveYear: 5220 },
    ownershipCost: {
      electricity5yr: 3200,
      insurance5yr: 8500,
      maintenance5yr: 4500,
      totalCost5yr: 52200,
      resalePercent: 40,
      resaleValue: 14400,
      netCost: 37800,
    },
    batteryDetails: {
      capacity: "71.4 kWh",
      realWorldRange: "200-220 mi",
      coldWeatherRange: "160-185 mi",
      degradationNote: "Same platform as bZ4X; AWD standard",
    },
    platforms: [
      { name: "Cars.com", url: "https://www.cars.com/shopping/subaru-solterra/" },
      { name: "Carvana", url: "https://www.carvana.com/cars/subaru-solterra" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/subaru/solterra" },
    ],
    trendPercent: -8.0,
    trendNote: "Big dealer markdowns to compete",
  },

  // === TRUCKS ===
  {
    id: "ford-f150-lightning-2024",
    brand: "Ford",
    model: "F-150 Lightning",
    year: 2024,
    bodyType: "truck",
    msrp: 49995,
    bestNewPrice: 44000,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/ford/f-150-lightning",
    bestUsedPrice: 36500,
    bestUsedPlatform: "CarMax",
    bestUsedUrl: "https://www.carmax.com/cars/ford/f-150-lightning",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 300,
    zeroToSixty: "4.0s",
    chargingSpeed: "120 mi",
    trueValueScore: 80,
    efficiency: 2.5,
    cargoSpace: "52 cu ft + frunk",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 130, annual: 1560, fiveYear: 7800 },
    ownershipCost: {
      electricity5yr: 3840,
      insurance5yr: 10000,
      maintenance5yr: 5000,
      totalCost5yr: 62840,
      resalePercent: 48,
      resaleValue: 21120,
      netCost: 41720,
    },
    batteryDetails: {
      capacity: "98 kWh",
      realWorldRange: "260-290 mi",
      coldWeatherRange: "200-235 mi",
      degradationNote: "~5% at 50k mi; towing significantly reduces range",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/ford/f-150-lightning" },
      { name: "CarMax", url: "https://www.carmax.com/cars/ford/f-150-lightning" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/ford-f_150_lightning/" },
      { name: "Carvana", url: "https://www.carvana.com/cars/ford-f-150-lightning" },
    ],
    trendPercent: -5.5,
    trendNote: "Electric truck prices falling fast",
  },
  {
    id: "rivian-r1t-2024",
    brand: "Rivian",
    model: "R1T",
    year: 2024,
    bodyType: "truck",
    msrp: 69900,
    bestNewPrice: 69900,
    bestNewPlatform: "Rivian.com",
    bestNewUrl: "https://rivian.com/r1t",
    bestUsedPrice: 55000,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/rivian-r1t",
    bestUsedYear: 2023,
    bestUsedMileage: "18k mi",
    range: 328,
    zeroToSixty: "3.0s",
    chargingSpeed: "140 mi",
    trueValueScore: 73,
    efficiency: 2.6,
    cargoSpace: "68 cu ft + bed",
    warranty: "5yr/60k bumper-to-bumper, 8yr/175k battery",
    fuelSavings: { monthly: 128, annual: 1536, fiveYear: 7680 },
    ownershipCost: {
      electricity5yr: 3692,
      insurance5yr: 11000,
      maintenance5yr: 4500,
      totalCost5yr: 89092,
      resalePercent: 52,
      resaleValue: 36348,
      netCost: 52744,
    },
    batteryDetails: {
      capacity: "135 kWh",
      realWorldRange: "290-320 mi",
      coldWeatherRange: "230-265 mi",
      degradationNote: "~4% at 50k mi; adventure-focused battery design",
    },
    platforms: [
      { name: "Rivian.com", url: "https://rivian.com/r1t" },
      { name: "Carvana", url: "https://www.carvana.com/cars/rivian-r1t" },
      { name: "CarMax", url: "https://www.carmax.com/cars/rivian/r1t" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/rivian/r1t" },
    ],
    trendPercent: 1.5,
    trendNote: "Demand holding steady for adventure truck",
  },
  {
    id: "chevy-silverado-ev-2024",
    brand: "Chevrolet",
    model: "Silverado EV",
    year: 2024,
    bodyType: "truck",
    msrp: 49995,
    bestNewPrice: 45000,
    bestNewPlatform: "AutoTrader",
    bestNewUrl: "https://www.autotrader.com/cars-for-sale/chevrolet/silverado-ev",
    bestUsedPrice: null,
    bestUsedPlatform: null,
    bestUsedUrl: "",
    bestUsedYear: null,
    bestUsedMileage: null,
    range: 390,
    zeroToSixty: "4.5s",
    chargingSpeed: "150 mi",
    trueValueScore: 82,
    efficiency: 2.7,
    cargoSpace: "60 cu ft + bed",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 130, annual: 1560, fiveYear: 7800 },
    ownershipCost: {
      electricity5yr: 3556,
      insurance5yr: 10000,
      maintenance5yr: 5000,
      totalCost5yr: 63556,
      resalePercent: 48,
      resaleValue: 21600,
      netCost: 41956,
    },
    batteryDetails: {
      capacity: "200 kWh",
      realWorldRange: "350-380 mi",
      coldWeatherRange: "275-310 mi",
      degradationNote: "Massive battery; too new for long-term data",
    },
    platforms: [
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/chevrolet/silverado-ev" },
      { name: "Cars.com", url: "https://www.cars.com/shopping/chevrolet-silverado_ev/" },
    ],
    trendPercent: -3.0,
    trendNote: "New to market with introductory pricing",
  },
  {
    id: "tesla-cybertruck-2024",
    brand: "Tesla",
    model: "Cybertruck",
    year: 2024,
    bodyType: "truck",
    msrp: 79990,
    bestNewPrice: 79990,
    bestNewPlatform: "Tesla.com",
    bestNewUrl: "https://www.tesla.com/cybertruck",
    bestUsedPrice: 85000,
    bestUsedPlatform: "CarGurus",
    bestUsedUrl: "https://www.cargurus.com/Cars/l-Used-Tesla-Cybertruck",
    bestUsedYear: 2024,
    bestUsedMileage: "5k mi",
    range: 340,
    zeroToSixty: "2.6s",
    chargingSpeed: "136 mi",
    trueValueScore: 55,
    efficiency: 2.5,
    cargoSpace: "68 cu ft + bed",
    warranty: "4yr/50k bumper-to-bumper, 8yr/150k battery",
    fuelSavings: { monthly: 130, annual: 1560, fiveYear: 7800 },
    ownershipCost: {
      electricity5yr: 3840,
      insurance5yr: 12000,
      maintenance5yr: 5000,
      totalCost5yr: 100830,
      resalePercent: 60,
      resaleValue: 47994,
      netCost: 52836,
    },
    batteryDetails: {
      capacity: "123 kWh",
      realWorldRange: "300-330 mi",
      coldWeatherRange: "235-275 mi",
      degradationNote: "Too new; early reports show typical Tesla longevity",
    },
    platforms: [
      { name: "Tesla.com", url: "https://www.tesla.com/cybertruck" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Tesla-Cybertruck" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/tesla/cybertruck" },
    ],
    trendPercent: 0,
    trendNote: "Used prices above MSRP due to demand",
  },

  // === HATCHBACK ===
  {
    id: "chevy-bolt-euv-2023",
    brand: "Chevrolet",
    model: "Bolt EUV",
    year: 2023,
    bodyType: "hatchback",
    msrp: 28795,
    bestNewPrice: null,
    bestNewPlatform: null,
    bestNewUrl: "",
    bestUsedPrice: 19800,
    bestUsedPlatform: "Carvana",
    bestUsedUrl: "https://www.carvana.com/cars/chevrolet-bolt-euv",
    bestUsedYear: 2023,
    bestUsedMileage: "15k mi",
    range: 247,
    zeroToSixty: "6.5s",
    chargingSpeed: "75 mi",
    trueValueScore: 91,
    efficiency: 3.7,
    cargoSpace: "57 cu ft",
    warranty: "3yr/36k bumper-to-bumper, 8yr/100k battery",
    fuelSavings: { monthly: 94, annual: 1128, fiveYear: 5640 },
    ownershipCost: {
      electricity5yr: 2595,
      insurance5yr: 7000,
      maintenance5yr: 4000,
      totalCost5yr: 33395,
      resalePercent: 35,
      resaleValue: 6930,
      netCost: 26465,
    },
    batteryDetails: {
      capacity: "65 kWh",
      realWorldRange: "220-240 mi",
      coldWeatherRange: "170-195 mi",
      degradationNote: "New battery pack (post-recall); excellent value",
    },
    platforms: [
      { name: "Carvana", url: "https://www.carvana.com/cars/chevrolet-bolt-euv" },
      { name: "CarMax", url: "https://www.carmax.com/cars/chevrolet/bolt-euv" },
      { name: "CarGurus", url: "https://www.cargurus.com/Cars/l-Used-Chevrolet-Bolt-EUV" },
      { name: "AutoTrader", url: "https://www.autotrader.com/cars-for-sale/chevrolet/bolt-euv" },
    ],
    trendPercent: -3.0,
    trendNote: "Discontinued but incredible used value",
    discontinued: true,
  },
];

// Gas car comparison data for savings calculator
export const GAS_CARS = [
  { name: "Honda Civic", mpg: 33 },
  { name: "Toyota Camry", mpg: 32 },
  { name: "Toyota RAV4", mpg: 30 },
  { name: "Honda CR-V", mpg: 30 },
  { name: "Ford F-150", mpg: 24 },
  { name: "Chevy Silverado", mpg: 23 },
  { name: "Toyota Highlander", mpg: 25 },
  { name: "BMW X5", mpg: 25 },
];

// Market pulse data for dashboard
export const MARKET_PULSE = [
  { model: "Tesla Model Y", percent: -4.2, note: "Prices dropping — great time to buy" },
  { model: "Tesla Model 3", percent: -3.8, note: "Used prices softening significantly" },
  { model: "Chevy Equinox EV", percent: -6.1, note: "Aggressive dealer discounts" },
  { model: "Ford Mustang Mach-E", percent: -5.5, note: "Steep markdowns on 2024 models" },
  { model: "Hyundai Ioniq 5", percent: -7.2, note: "Best deals in the EV market right now" },
  { model: "Kia EV6", percent: -4.9, note: "Competitive pricing across dealers" },
  { model: "BMW iX", percent: -8.3, note: "Luxury EVs seeing biggest drops" },
  { model: "Rivian R1S", percent: 2.1, note: "Limited supply keeping prices firm" },
  { model: "Toyota bZ4X", percent: -9.5, note: "Deep discounts to move inventory" },
  { model: "Nissan Ariya", percent: -6.8, note: "Undervalued — strong specs for the price" },
];

// Unique brands for filter
export const EV_BRANDS = [...new Set(EV_DEALS.map((d) => d.brand))].sort();
