export interface OBDCode {
  code: string;
  title: string;
  description: string;
  severity: "Low" | "Medium" | "High" | "Critical";
  system: string;
  commonCauses: string[];
  symptoms: string[];
  estimatedCostMin: number;
  estimatedCostMax: number;
  difficulty: "Easy" | "Moderate" | "Advanced" | "Professional";
}

export const OBD_CODES: OBDCode[] = [
  // === ENGINE MISFIRES (P03xx) ===
  { code: "P0300", title: "Random/Multiple Cylinder Misfire Detected", description: "Your engine's computer has detected misfires happening across multiple cylinders without a clear pattern. This means the fuel-air mixture isn't igniting properly in several cylinders, which can cause rough running, poor fuel economy, and potential catalytic converter damage if left unrepaired.", severity: "High", system: "Engine", commonCauses: ["Worn or fouled spark plugs", "Faulty ignition coils", "Vacuum leaks in the intake manifold", "Low fuel pressure or clogged fuel injectors", "Worn valve seals or head gasket issues"], symptoms: ["Engine runs rough or shakes at idle", "Check engine light flashing", "Loss of power during acceleration", "Poor fuel economy"], estimatedCostMin: 150, estimatedCostMax: 1000, difficulty: "Moderate" },
  { code: "P0301", title: "Cylinder 1 Misfire Detected", description: "The engine control module has detected a misfire specifically in cylinder 1. A single-cylinder misfire is typically easier to diagnose than a random misfire because the problem is isolated to the components serving that one cylinder.", severity: "High", system: "Engine", commonCauses: ["Failed spark plug in cylinder 1", "Faulty ignition coil for cylinder 1", "Clogged or leaking fuel injector", "Low compression in cylinder 1", "Vacuum leak near cylinder 1 intake runner"], symptoms: ["Engine shakes or vibrates at idle", "Flashing check engine light", "Reduced power", "Rough acceleration"], estimatedCostMin: 100, estimatedCostMax: 800, difficulty: "Moderate" },
  { code: "P0302", title: "Cylinder 2 Misfire Detected", description: "A misfire has been detected in cylinder 2. The ignition or fuel delivery system for this specific cylinder is not functioning correctly, causing incomplete combustion.", severity: "High", system: "Engine", commonCauses: ["Bad spark plug in cylinder 2", "Faulty ignition coil", "Clogged fuel injector", "Low compression", "Wiring issue to cylinder 2 components"], symptoms: ["Engine vibration at idle", "Flashing check engine light", "Loss of power", "Increased emissions"], estimatedCostMin: 100, estimatedCostMax: 800, difficulty: "Moderate" },
  { code: "P0303", title: "Cylinder 3 Misfire Detected", description: "Cylinder 3 is experiencing misfires. The engine control module monitors crankshaft speed variations to detect which cylinder is not firing properly.", severity: "High", system: "Engine", commonCauses: ["Worn spark plug in cylinder 3", "Failed ignition coil", "Fuel injector malfunction", "Intake manifold leak", "Mechanical engine issue"], symptoms: ["Rough idle", "Check engine light flashing", "Power loss", "Engine vibration"], estimatedCostMin: 100, estimatedCostMax: 800, difficulty: "Moderate" },
  { code: "P0304", title: "Cylinder 4 Misfire Detected", description: "The engine control module has identified misfires occurring in cylinder 4. Like other single-cylinder misfires, this points to a localized issue with ignition, fuel delivery, or mechanical compression in that cylinder.", severity: "High", system: "Engine", commonCauses: ["Spark plug failure in cylinder 4", "Ignition coil failure", "Fuel injector issue", "Compression loss", "Damaged spark plug wire"], symptoms: ["Rough running engine", "Flashing check engine light", "Hesitation during acceleration", "Poor fuel economy"], estimatedCostMin: 100, estimatedCostMax: 800, difficulty: "Moderate" },
  { code: "P0305", title: "Cylinder 5 Misfire Detected", description: "A misfire has been detected in cylinder 5. This code typically appears on V6, V8, or inline-6 engines and indicates that cylinder 5 is not contributing its share of power to the engine.", severity: "High", system: "Engine", commonCauses: ["Worn spark plug", "Failed ignition coil", "Fuel injector malfunction", "Low compression", "Valve train issue"], symptoms: ["Engine runs rough", "Flashing check engine light", "Loss of power", "Vibration at idle"], estimatedCostMin: 100, estimatedCostMax: 900, difficulty: "Moderate" },
  { code: "P0306", title: "Cylinder 6 Misfire Detected", description: "Cylinder 6 is experiencing combustion failures. On V6 and V8 engines, cylinder 6 is often on the rear bank, which can make spark plug and coil access more difficult.", severity: "High", system: "Engine", commonCauses: ["Spark plug or coil failure", "Fuel injector clog", "Vacuum leak", "Low compression", "Wiring harness damage"], symptoms: ["Rough idle and vibration", "Check engine light flashing", "Reduced power output", "Poor fuel efficiency"], estimatedCostMin: 100, estimatedCostMax: 900, difficulty: "Moderate" },

  // === FUEL SYSTEM (P01xx, P02xx) ===
  { code: "P0100", title: "Mass Air Flow Circuit Malfunction", description: "The Mass Air Flow (MAF) sensor is not sending a reliable signal to the engine computer. The MAF sensor measures the amount of air entering the engine, which is critical for calculating the correct fuel-to-air ratio.", severity: "Medium", system: "Fuel System", commonCauses: ["Dirty or contaminated MAF sensor", "Damaged MAF sensor wiring", "Air filter is clogged or improperly installed", "Vacuum leaks after the MAF sensor", "Faulty MAF sensor"], symptoms: ["Engine stalls or hesitates", "Rough idle", "Poor acceleration", "Decreased fuel economy"], estimatedCostMin: 100, estimatedCostMax: 400, difficulty: "Easy" },
  { code: "P0101", title: "Mass Air Flow Circuit Range/Performance", description: "The MAF sensor reading is outside the expected range for the current engine operating conditions. The sensor may be working but providing inaccurate readings that cause poor engine performance.", severity: "Medium", system: "Fuel System", commonCauses: ["Contaminated MAF sensor element", "Air leaks between the MAF and throttle body", "Clogged air filter restricting flow", "Faulty MAF sensor", "Exhaust leak near O2 sensor"], symptoms: ["Rough or unstable idle", "Hesitation on acceleration", "Black smoke from exhaust", "Hard starting"], estimatedCostMin: 80, estimatedCostMax: 400, difficulty: "Easy" },
  { code: "P0106", title: "MAP/Barometric Pressure Circuit Range/Performance", description: "The Manifold Absolute Pressure (MAP) sensor is reading outside its expected range. The MAP sensor helps the engine computer determine engine load and adjust fuel delivery accordingly.", severity: "Medium", system: "Fuel System", commonCauses: ["Faulty MAP sensor", "Vacuum hose leak or disconnection", "Clogged vacuum port", "Wiring issue to MAP sensor", "Intake manifold gasket leak"], symptoms: ["Rough idle", "Stalling", "Poor fuel economy", "Lack of power"], estimatedCostMin: 75, estimatedCostMax: 350, difficulty: "Easy" },
  { code: "P0110", title: "Intake Air Temperature Sensor Circuit Malfunction", description: "The Intake Air Temperature (IAT) sensor circuit is not providing a valid signal. This sensor measures the temperature of incoming air to help the engine computer adjust the fuel mixture.", severity: "Low", system: "Fuel System", commonCauses: ["Faulty IAT sensor", "Damaged or corroded wiring", "Poor electrical connection", "Sensor contamination", "Open or short circuit"], symptoms: ["Slightly rough idle", "Minor fuel economy decrease", "Check engine light on", "Hard starting in extreme temperatures"], estimatedCostMin: 50, estimatedCostMax: 200, difficulty: "Easy" },
  { code: "P0113", title: "Intake Air Temperature Sensor Circuit High Input", description: "The IAT sensor is reporting an unusually high voltage, indicating extremely cold air temperatures that don't match actual conditions. This is typically an electrical issue rather than a real temperature problem.", severity: "Low", system: "Fuel System", commonCauses: ["Open circuit in IAT sensor wiring", "Failed IAT sensor", "Corroded connector pins", "Damaged wiring harness", "Poor ground connection"], symptoms: ["Rich fuel mixture", "Slightly decreased fuel economy", "Check engine light on", "Minor performance issues"], estimatedCostMin: 50, estimatedCostMax: 200, difficulty: "Easy" },
  { code: "P0120", title: "Throttle Position Sensor Circuit Malfunction", description: "The Throttle Position Sensor (TPS) is not providing a proper signal to the engine computer. The TPS tells the computer how far open the throttle is, which is essential for proper fuel and ignition timing.", severity: "High", system: "Fuel System", commonCauses: ["Worn or faulty TPS", "Damaged wiring or connector", "Throttle body mechanical issue", "Poor ground connection", "Corrosion on sensor contacts"], symptoms: ["Engine surging or hesitation", "Sudden idle speed changes", "Vehicle may enter limp mode", "Poor throttle response"], estimatedCostMin: 100, estimatedCostMax: 500, difficulty: "Moderate" },
  { code: "P0128", title: "Coolant Thermostat Below Regulating Temperature", description: "Your engine is taking too long to reach its normal operating temperature. The thermostat, which controls coolant flow, is likely stuck open, allowing coolant to circulate too freely and preventing the engine from warming up efficiently.", severity: "Low", system: "Engine", commonCauses: ["Thermostat stuck in the open position", "Faulty engine coolant temperature sensor", "Low coolant level", "Cooling fan running constantly", "Thermostat housing leak"], symptoms: ["Engine takes a long time to warm up", "Heater blows lukewarm air", "Slightly higher fuel consumption", "Temperature gauge stays low"], estimatedCostMin: 100, estimatedCostMax: 350, difficulty: "Moderate" },
  { code: "P0131", title: "O2 Sensor Circuit Low Voltage (Bank 1, Sensor 1)", description: "The upstream oxygen sensor on bank 1 is consistently reading a lean condition (low voltage). This sensor is critical for the engine computer to maintain the proper air-fuel ratio.", severity: "Medium", system: "Fuel System", commonCauses: ["Faulty O2 sensor", "Vacuum leak causing lean condition", "Low fuel pressure", "Exhaust leak before the sensor", "Wiring damage to the O2 sensor"], symptoms: ["Poor fuel economy", "Rough idle", "Hesitation on acceleration", "Failed emissions test"], estimatedCostMin: 150, estimatedCostMax: 500, difficulty: "Moderate" },
  { code: "P0133", title: "O2 Sensor Circuit Slow Response (Bank 1, Sensor 1)", description: "The upstream oxygen sensor on bank 1 is switching between rich and lean readings too slowly. A healthy O2 sensor should toggle rapidly, and slow response leads to inefficient fuel mixture adjustments.", severity: "Medium", system: "Fuel System", commonCauses: ["Aging or contaminated O2 sensor", "Exhaust leak near the sensor", "Fuel contamination", "Sensor wiring issue", "Catalytic converter starting to fail"], symptoms: ["Decreased fuel economy", "Rough idle", "Sluggish performance", "May fail emissions inspection"], estimatedCostMin: 150, estimatedCostMax: 450, difficulty: "Moderate" },
  { code: "P0135", title: "O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)", description: "The heater element inside the oxygen sensor on bank 1 is not functioning properly. O2 sensors need to reach high temperatures quickly to provide accurate readings, and the built-in heater helps them do this.", severity: "Medium", system: "Fuel System", commonCauses: ["Failed O2 sensor heater element", "Blown fuse for O2 sensor heater circuit", "Wiring damage or corrosion", "Poor electrical connection", "Faulty engine control module relay"], symptoms: ["Check engine light on", "Slightly increased emissions", "Minor fuel economy decrease", "Extended cold-start enrichment"], estimatedCostMin: 100, estimatedCostMax: 400, difficulty: "Moderate" },
  { code: "P0137", title: "O2 Sensor Circuit Low Voltage (Bank 1, Sensor 2)", description: "The downstream oxygen sensor (after the catalytic converter) on bank 1 is consistently reading low voltage. This sensor monitors catalytic converter efficiency.", severity: "Medium", system: "Emissions", commonCauses: ["Faulty downstream O2 sensor", "Exhaust leak", "Catalytic converter degradation", "Wiring or connector issue", "Engine running lean"], symptoms: ["Check engine light on", "Poor fuel economy", "May fail emissions test", "Reduced performance"], estimatedCostMin: 150, estimatedCostMax: 450, difficulty: "Moderate" },
  { code: "P0141", title: "O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 2)", description: "The heater circuit for the downstream oxygen sensor on bank 1 has malfunctioned. This sensor monitors catalytic converter efficiency, and its heater helps it reach operating temperature quickly.", severity: "Low", system: "Emissions", commonCauses: ["Failed heater element in O2 sensor", "Blown fuse", "Wiring short or open circuit", "Corroded connector", "Faulty PCM driver circuit"], symptoms: ["Check engine light on", "Slightly higher emissions", "No noticeable drivability issues", "May fail emissions test"], estimatedCostMin: 100, estimatedCostMax: 400, difficulty: "Moderate" },
  { code: "P0171", title: "System Too Lean (Bank 1)", description: "The engine is running with too much air and not enough fuel on bank 1. The engine computer is adding extra fuel to compensate, but cannot correct the lean condition enough. Running lean can cause engine overheating and potential damage over time.", severity: "Medium", system: "Fuel System", commonCauses: ["Vacuum leak in the intake system", "Faulty or dirty MAF sensor", "Weak fuel pump or clogged fuel filter", "Leaking fuel injector", "PCV valve malfunction"], symptoms: ["Rough or high idle", "Hesitation during acceleration", "Poor fuel economy despite lean condition", "Engine may surge"], estimatedCostMin: 100, estimatedCostMax: 600, difficulty: "Moderate" },
  { code: "P0172", title: "System Too Rich (Bank 1)", description: "The engine is receiving too much fuel relative to air on bank 1. The computer has tried to reduce fuel delivery but cannot lean out the mixture enough. Excess fuel washes oil from cylinder walls and can damage the catalytic converter.", severity: "Medium", system: "Fuel System", commonCauses: ["Dirty or faulty MAF sensor", "Leaking fuel injector", "Faulty fuel pressure regulator", "Stuck-open purge valve", "Faulty O2 sensor giving false lean reading"], symptoms: ["Strong fuel smell from exhaust", "Black smoke from tailpipe", "Fouled spark plugs", "Poor fuel economy"], estimatedCostMin: 100, estimatedCostMax: 600, difficulty: "Moderate" },
  { code: "P0174", title: "System Too Lean (Bank 2)", description: "Bank 2 of the engine is running lean, meaning there is too much air relative to fuel. On V-configuration engines, bank 2 is the side that does not contain cylinder 1. The causes are similar to P0171 but isolated to bank 2.", severity: "Medium", system: "Fuel System", commonCauses: ["Vacuum leak on bank 2 side", "Dirty MAF sensor", "Low fuel pressure", "Leaking intake gasket on bank 2", "Faulty O2 sensor on bank 2"], symptoms: ["Rough idle", "Hesitation", "Poor fuel economy", "Engine runs hot"], estimatedCostMin: 100, estimatedCostMax: 600, difficulty: "Moderate" },
  { code: "P0175", title: "System Too Rich (Bank 2)", description: "Bank 2 of the engine is running rich with excessive fuel. The engine computer cannot reduce fuel delivery enough to achieve the proper air-fuel ratio on this bank.", severity: "Medium", system: "Fuel System", commonCauses: ["Leaking fuel injector on bank 2", "Faulty MAF sensor", "Stuck fuel pressure regulator", "Faulty O2 sensor on bank 2", "EVAP purge valve stuck open"], symptoms: ["Fuel smell", "Black exhaust smoke", "Spark plug fouling", "Poor fuel economy"], estimatedCostMin: 100, estimatedCostMax: 600, difficulty: "Moderate" },
  { code: "P0191", title: "Fuel Rail Pressure Sensor Circuit Range/Performance", description: "The fuel rail pressure sensor is reporting readings that are outside the expected range. This sensor monitors fuel pressure in the fuel rail to ensure proper fuel delivery to the injectors.", severity: "Medium", system: "Fuel System", commonCauses: ["Faulty fuel rail pressure sensor", "Weak fuel pump", "Clogged fuel filter", "Fuel line restriction", "Wiring issue"], symptoms: ["Hard starting", "Engine stalling", "Loss of power", "Poor fuel economy"], estimatedCostMin: 150, estimatedCostMax: 600, difficulty: "Moderate" },
  { code: "P0200", title: "Injector Circuit Malfunction", description: "The engine computer has detected a general malfunction in the fuel injector circuit. This could affect one or more injectors and impacts the engine's ability to deliver the correct amount of fuel.", severity: "High", system: "Fuel System", commonCauses: ["Faulty fuel injector", "Damaged wiring to injector", "Poor electrical connection", "Failed injector driver in PCM", "Short circuit in harness"], symptoms: ["Engine misfire", "Rough idle", "Loss of power", "Poor fuel economy"], estimatedCostMin: 200, estimatedCostMax: 800, difficulty: "Advanced" },
  { code: "P0217", title: "Engine Coolant Over Temperature", description: "The engine coolant temperature has exceeded the maximum safe threshold. This is a serious condition that can lead to engine damage including warped cylinder heads and blown head gaskets if not addressed immediately.", severity: "Critical", system: "Engine", commonCauses: ["Low coolant level or leak", "Failed water pump", "Thermostat stuck closed", "Radiator blockage", "Failed cooling fan"], symptoms: ["Temperature gauge in the red zone", "Steam from under the hood", "Sweet coolant smell", "Engine power reduction or shutdown"], estimatedCostMin: 200, estimatedCostMax: 1500, difficulty: "Advanced" },
  { code: "P0299", title: "Turbo/Supercharger Underboost", description: "The turbocharger or supercharger is not producing the expected amount of boost pressure. The engine is not receiving the forced air it needs for optimal performance.", severity: "Medium", system: "Engine", commonCauses: ["Boost leak in intercooler piping", "Failed wastegate actuator", "Turbo bearing wear", "Clogged air filter", "Faulty boost pressure sensor"], symptoms: ["Noticeable loss of power", "Slower acceleration", "Turbo whistle or unusual noise", "Check engine light on"], estimatedCostMin: 200, estimatedCostMax: 2000, difficulty: "Advanced" },

  // === EMISSIONS SYSTEM (P04xx) ===
  { code: "P0401", title: "Exhaust Gas Recirculation Flow Insufficient", description: "The EGR (Exhaust Gas Recirculation) system is not flowing enough exhaust gas back into the intake manifold. The EGR system reduces nitrogen oxide emissions by cooling combustion temperatures.", severity: "Medium", system: "Emissions", commonCauses: ["Carbon buildup blocking EGR passages", "Stuck or failed EGR valve", "Clogged EGR tube", "Faulty EGR position sensor", "Vacuum supply issue to EGR valve"], symptoms: ["Check engine light on", "Engine knocking or pinging", "Rough idle", "Failed emissions test"], estimatedCostMin: 150, estimatedCostMax: 500, difficulty: "Moderate" },
  { code: "P0402", title: "Exhaust Gas Recirculation Flow Excessive", description: "Too much exhaust gas is being recirculated into the engine intake. This creates an overly diluted air-fuel mixture that hurts engine performance and can cause stalling.", severity: "Medium", system: "Emissions", commonCauses: ["EGR valve stuck open", "Carbon holding the valve open", "Faulty EGR control solenoid", "Vacuum line routing error", "Faulty DPFE sensor"], symptoms: ["Rough idle or stalling", "Engine hesitation", "Poor acceleration", "Check engine light on"], estimatedCostMin: 150, estimatedCostMax: 450, difficulty: "Moderate" },
  { code: "P0420", title: "Catalyst System Efficiency Below Threshold (Bank 1)", description: "The catalytic converter on bank 1 is not cleaning exhaust gases as effectively as it should. The downstream oxygen sensor is seeing readings too similar to the upstream sensor, meaning the converter is not doing its job of converting harmful emissions.", severity: "High", system: "Emissions", commonCauses: ["Worn-out catalytic converter", "Engine misfire damaging the converter", "Oil or coolant contamination of the converter", "Exhaust leaks before or after the converter", "Faulty downstream O2 sensor giving false reading"], symptoms: ["Check engine light on", "Sulfur or rotten egg smell", "Reduced engine performance", "Failed emissions inspection"], estimatedCostMin: 500, estimatedCostMax: 2500, difficulty: "Professional" },
  { code: "P0430", title: "Catalyst System Efficiency Below Threshold (Bank 2)", description: "The catalytic converter on bank 2 is underperforming. Similar to P0420, this means the converter on the opposite bank is not efficiently converting harmful exhaust gases. On V-engines, both banks have their own converter.", severity: "High", system: "Emissions", commonCauses: ["Catalytic converter deterioration", "Engine running rich fouling the converter", "Oil burning contaminating the converter", "Exhaust manifold leak", "Downstream O2 sensor failure"], symptoms: ["Check engine light on", "Rotten egg smell from exhaust", "Decreased performance", "Failed emissions test"], estimatedCostMin: 500, estimatedCostMax: 2500, difficulty: "Professional" },
  { code: "P0440", title: "Evaporative Emission System Malfunction", description: "A general malfunction has been detected in the EVAP system, which captures fuel vapors from the gas tank and prevents them from escaping into the atmosphere. This is a broad code that indicates the system is not sealing or purging correctly.", severity: "Low", system: "Emissions", commonCauses: ["Loose or damaged gas cap", "Cracked or disconnected EVAP hose", "Faulty purge control valve", "Faulty vent control valve", "Leak in charcoal canister"], symptoms: ["Check engine light on", "Fuel smell near vehicle", "No noticeable drivability issues", "Failed emissions test"], estimatedCostMin: 75, estimatedCostMax: 400, difficulty: "Moderate" },
  { code: "P0441", title: "Evaporative Emission System Incorrect Purge Flow", description: "The EVAP system purge flow is not within the expected range. The purge valve should open at specific times to draw fuel vapors from the charcoal canister into the engine to be burned.", severity: "Low", system: "Emissions", commonCauses: ["Faulty purge valve (stuck open or closed)", "Vacuum line leak or blockage", "Damaged charcoal canister", "EVAP system wiring issue", "Faulty EVAP pressure sensor"], symptoms: ["Check engine light on", "Slight fuel odor", "No significant drivability impact", "May fail emissions test"], estimatedCostMin: 75, estimatedCostMax: 350, difficulty: "Moderate" },
  { code: "P0442", title: "Evaporative Emission System Leak Detected (Small)", description: "A small leak has been detected in the EVAP system. The system performs self-tests by pressurizing or creating a vacuum in the fuel vapor system, and a small hole or crack is allowing pressure to escape.", severity: "Low", system: "Emissions", commonCauses: ["Loose or worn gas cap seal", "Small crack in EVAP hose", "Faulty purge or vent valve with slight leak", "Fuel tank filler neck corrosion", "Charcoal canister crack"], symptoms: ["Check engine light on", "No noticeable drivability issues", "Slight fuel smell possible", "Failed emissions test"], estimatedCostMin: 50, estimatedCostMax: 400, difficulty: "Moderate" },
  { code: "P0443", title: "Evaporative Emission System Purge Control Valve Circuit", description: "The electrical circuit controlling the EVAP purge valve has a malfunction. The purge valve controls when fuel vapors are drawn from the charcoal canister into the engine.", severity: "Low", system: "Emissions", commonCauses: ["Faulty purge control valve", "Wiring damage to the purge valve", "Poor electrical connector", "Blown fuse", "PCM driver circuit failure"], symptoms: ["Check engine light on", "Minor increase in emissions", "No significant drivability issues", "Failed emissions test"], estimatedCostMin: 75, estimatedCostMax: 300, difficulty: "Easy" },
  { code: "P0446", title: "Evaporative Emission System Vent Control Circuit", description: "The vent control valve circuit in the EVAP system has malfunctioned. The vent valve allows air into the charcoal canister during purging and seals the system during leak tests.", severity: "Low", system: "Emissions", commonCauses: ["Faulty vent control valve", "Blocked vent filter", "Wiring or connector problem", "Charcoal canister obstruction", "Spider or debris blocking vent"], symptoms: ["Check engine light on", "Difficulty refueling (pump clicks off)", "No drivability issues", "Failed emissions test"], estimatedCostMin: 75, estimatedCostMax: 350, difficulty: "Moderate" },
  { code: "P0449", title: "Evaporative Emission System Vent Valve/Solenoid Circuit", description: "The EVAP vent valve solenoid circuit has an electrical malfunction. This valve is typically located near the charcoal canister and controls the venting of the EVAP system.", severity: "Low", system: "Emissions", commonCauses: ["Failed vent valve solenoid", "Wiring short or open", "Corroded electrical connector", "PCM issue", "Physical damage to solenoid"], symptoms: ["Check engine light on", "Possible fuel smell", "No drivability symptoms", "May fail emissions testing"], estimatedCostMin: 75, estimatedCostMax: 300, difficulty: "Easy" },
  { code: "P0455", title: "Evaporative Emission System Leak Detected (Large)", description: "A large leak has been detected in the EVAP system. Unlike the small leak code P0442, a large leak suggests a significant opening in the vapor recovery system, often as simple as a missing gas cap.", severity: "Low", system: "Emissions", commonCauses: ["Gas cap missing or not tightened", "Gas cap seal cracked or worn", "Disconnected or broken EVAP hose", "Stuck-open purge or vent valve", "Cracked charcoal canister"], symptoms: ["Check engine light on", "Fuel odor near the vehicle", "No significant drivability issues", "Failed emissions test"], estimatedCostMin: 25, estimatedCostMax: 300, difficulty: "Easy" },
  { code: "P0456", title: "Evaporative Emission System Leak Detected (Very Small)", description: "A very small leak has been found in the EVAP system. This is the smallest leak size the system can detect and is often caused by minor seal degradation or tiny cracks in hoses.", severity: "Low", system: "Emissions", commonCauses: ["Slightly worn gas cap O-ring", "Hairline crack in EVAP hose", "Minor seal degradation", "Fuel tank pressure sensor issue", "Age-related rubber deterioration"], symptoms: ["Check engine light on", "No performance impact", "No noticeable fuel smell", "May fail emissions test"], estimatedCostMin: 50, estimatedCostMax: 350, difficulty: "Moderate" },

  // === IGNITION SYSTEM ===
  { code: "P0325", title: "Knock Sensor 1 Circuit Malfunction", description: "The knock sensor on bank 1 is not providing a valid signal. This sensor detects engine knock (detonation) and tells the computer to retard ignition timing to prevent engine damage.", severity: "Medium", system: "Engine", commonCauses: ["Failed knock sensor", "Damaged wiring to knock sensor", "Loose sensor mounting", "Corroded connector", "Engine mechanical noise confusing the sensor"], symptoms: ["Check engine light on", "Engine may feel sluggish (retarded timing)", "Possible engine knock under load", "Reduced fuel economy"], estimatedCostMin: 150, estimatedCostMax: 500, difficulty: "Moderate" },
  { code: "P0335", title: "Crankshaft Position Sensor Circuit Malfunction", description: "The crankshaft position sensor is not sending a reliable signal. This sensor is critical because the engine computer uses it to determine engine speed and crankshaft position for fuel injection and ignition timing.", severity: "Critical", system: "Engine", commonCauses: ["Failed crankshaft position sensor", "Damaged reluctor ring/tone wheel", "Wiring damage or corrosion", "Excessive crankshaft end play", "Oil contamination on sensor"], symptoms: ["Engine cranks but won't start", "Intermittent stalling", "Engine cuts out while driving", "Rough running and misfires"], estimatedCostMin: 150, estimatedCostMax: 500, difficulty: "Moderate" },
  { code: "P0340", title: "Camshaft Position Sensor Circuit Malfunction", description: "The camshaft position sensor circuit has malfunctioned. This sensor tells the engine computer the position of the camshaft, which is essential for sequential fuel injection and variable valve timing.", severity: "High", system: "Engine", commonCauses: ["Failed camshaft position sensor", "Damaged or stretched timing chain/belt", "Wiring issue to the sensor", "Worn sensor reluctor wheel", "Oil contamination"], symptoms: ["Hard starting or no start", "Rough idle", "Stalling", "Check engine light on"], estimatedCostMin: 100, estimatedCostMax: 400, difficulty: "Moderate" },
  { code: "P0341", title: "Camshaft Position Sensor Range/Performance", description: "The camshaft position sensor signal is present but is not matching expected values. The sensor is working but the timing relationship between the camshaft and crankshaft may be off.", severity: "High", system: "Engine", commonCauses: ["Stretched or skipped timing chain", "Worn camshaft phaser/actuator", "Faulty CMP sensor", "Incorrect valve timing", "Tone wheel damage"], symptoms: ["Poor performance", "Hard starting", "Rough idle", "Possible engine noise"], estimatedCostMin: 150, estimatedCostMax: 1200, difficulty: "Advanced" },

  // === COOLING SYSTEM ===
  { code: "P0115", title: "Engine Coolant Temperature Sensor Circuit", description: "The engine coolant temperature (ECT) sensor circuit is malfunctioning. This sensor tells the computer how hot or cold the engine is, which affects fuel mixture, ignition timing, and transmission shift points.", severity: "Medium", system: "Engine", commonCauses: ["Faulty ECT sensor", "Damaged wiring or connector", "Corroded terminals", "Short circuit in harness", "Low coolant level exposing sensor"], symptoms: ["Incorrect temperature gauge reading", "Poor fuel economy", "Hard starting", "Electric fans running constantly or not at all"], estimatedCostMin: 75, estimatedCostMax: 300, difficulty: "Easy" },
  { code: "P0116", title: "Engine Coolant Temperature Sensor Range/Performance", description: "The ECT sensor readings do not match expected warm-up patterns. The computer compares the coolant temperature to the intake air temperature at start-up and monitors the warm-up rate.", severity: "Medium", system: "Engine", commonCauses: ["Thermostat stuck open or closed", "Faulty ECT sensor", "Low coolant level", "Air pocket in cooling system", "Radiator fan malfunction"], symptoms: ["Temperature gauge reads incorrectly", "Engine runs rough when cold", "Overheating or slow warm-up", "Poor heater performance"], estimatedCostMin: 75, estimatedCostMax: 400, difficulty: "Easy" },

  // === TRANSMISSION (P07xx) ===
  { code: "P0700", title: "Transmission Control System Malfunction", description: "The engine computer has received a signal from the transmission control module indicating a transmission-related problem. This is a generic code that means additional transmission-specific codes are stored.", severity: "High", system: "Transmission", commonCauses: ["Another specific transmission code is set", "Transmission control module communication issue", "Wiring problem between TCM and PCM", "Low transmission fluid", "Internal transmission failure"], symptoms: ["Check engine light on", "Transmission shifting problems", "Vehicle may enter limp mode", "Harsh or delayed shifts"], estimatedCostMin: 100, estimatedCostMax: 3000, difficulty: "Professional" },
  { code: "P0705", title: "Transmission Range Sensor Circuit Malfunction", description: "The transmission range sensor (also called the neutral safety switch or PRNDL switch) is not sending a valid signal. This sensor tells the computer which gear position the shifter is in.", severity: "High", system: "Transmission", commonCauses: ["Faulty transmission range sensor", "Misadjusted shift linkage", "Damaged wiring or connector", "Internal transmission issue", "Corroded electrical contacts"], symptoms: ["Vehicle won't start in Park or Neutral", "Incorrect gear display on dashboard", "Harsh or incorrect shifting", "Backup lights not working"], estimatedCostMin: 150, estimatedCostMax: 600, difficulty: "Moderate" },
  { code: "P0715", title: "Input/Turbine Speed Sensor Circuit Malfunction", description: "The transmission input speed sensor is not functioning correctly. This sensor measures the rotational speed of the torque converter turbine shaft, which the computer uses to calculate gear ratios and shift timing.", severity: "High", system: "Transmission", commonCauses: ["Failed input speed sensor", "Damaged tone ring", "Wiring or connector issue", "Metallic debris on sensor", "Internal transmission damage"], symptoms: ["Erratic or harsh shifting", "Speedometer malfunction", "Transmission slipping", "Check engine light and limp mode"], estimatedCostMin: 200, estimatedCostMax: 800, difficulty: "Advanced" },
  { code: "P0720", title: "Output Speed Sensor Circuit Malfunction", description: "The transmission output speed sensor is malfunctioning. This sensor measures the speed of the output shaft and is used by the computer to determine vehicle speed and control shift points.", severity: "High", system: "Transmission", commonCauses: ["Failed output speed sensor", "Damaged wiring", "Metallic contamination on sensor", "Damaged tone ring", "Transmission fluid contamination"], symptoms: ["Speedometer not working", "Harsh or delayed shifts", "Transmission may not shift", "ABS/traction control lights on"], estimatedCostMin: 150, estimatedCostMax: 700, difficulty: "Advanced" },
  { code: "P0730", title: "Incorrect Gear Ratio", description: "The transmission is not achieving the expected gear ratio. The computer compares input and output speed sensors and has determined that the gear ratio does not match what it commanded.", severity: "Critical", system: "Transmission", commonCauses: ["Low or contaminated transmission fluid", "Worn clutch packs or bands", "Faulty solenoid pack", "Internal transmission mechanical failure", "Torque converter issue"], symptoms: ["Transmission slipping", "Harsh or flared shifts", "Vehicle won't shift properly", "Reduced power and limp mode"], estimatedCostMin: 500, estimatedCostMax: 4000, difficulty: "Professional" },
  { code: "P0740", title: "Torque Converter Clutch Circuit Malfunction", description: "The torque converter clutch (TCC) solenoid circuit has a malfunction. The TCC locks the torque converter at highway speeds to improve fuel economy by creating a direct mechanical connection.", severity: "Medium", system: "Transmission", commonCauses: ["Faulty TCC solenoid", "Wiring issue to the solenoid", "Contaminated transmission fluid", "Internal torque converter failure", "PCM driver circuit issue"], symptoms: ["Decreased highway fuel economy", "Engine stalls when coming to a stop", "Slight shudder at highway speeds", "Check engine light on"], estimatedCostMin: 200, estimatedCostMax: 1200, difficulty: "Professional" },
  { code: "P0741", title: "Torque Converter Clutch Circuit Performance or Stuck Off", description: "The torque converter clutch is not engaging when commanded. The computer expects the input and output speeds to match when the TCC is commanded on, but they do not.", severity: "Medium", system: "Transmission", commonCauses: ["Worn TCC friction material", "Faulty TCC solenoid", "Low or degraded transmission fluid", "Internal converter damage", "Valve body issue"], symptoms: ["Reduced fuel economy", "Transmission slipping at highway speed", "Slight shudder", "Higher engine RPM than normal at cruise"], estimatedCostMin: 200, estimatedCostMax: 2000, difficulty: "Professional" },
  { code: "P0750", title: "Shift Solenoid A Malfunction", description: "Shift solenoid A in the transmission is not functioning correctly. Shift solenoids control the flow of transmission fluid to engage different gear sets.", severity: "High", system: "Transmission", commonCauses: ["Failed shift solenoid A", "Wiring issue to solenoid", "Contaminated transmission fluid", "Valve body obstruction", "PCM driver failure"], symptoms: ["Hard or delayed 1-2 shift", "Transmission stuck in one gear", "Limp mode engagement", "Check engine light on"], estimatedCostMin: 200, estimatedCostMax: 1000, difficulty: "Professional" },

  // === THROTTLE AND AIR SYSTEM ===
  { code: "P0500", title: "Vehicle Speed Sensor Malfunction", description: "The vehicle speed sensor (VSS) is not sending a valid signal to the engine computer. This sensor provides critical information for speedometer operation, transmission shifting, cruise control, and ABS function.", severity: "Medium", system: "Engine", commonCauses: ["Failed vehicle speed sensor", "Damaged wiring or connector", "Faulty instrument cluster", "Transmission output shaft issue", "PCM input circuit failure"], symptoms: ["Speedometer not working or erratic", "Transmission shifts erratically", "Cruise control won't engage", "ABS light may come on"], estimatedCostMin: 100, estimatedCostMax: 400, difficulty: "Moderate" },
  { code: "P0505", title: "Idle Air Control System Malfunction", description: "The idle air control (IAC) valve or system is not functioning correctly. The IAC valve regulates the amount of air bypassing the throttle plate to control idle speed.", severity: "Medium", system: "Engine", commonCauses: ["Carbon-clogged IAC valve", "Faulty IAC valve motor", "Vacuum leak", "Dirty throttle body", "Wiring issue to IAC valve"], symptoms: ["Erratic idle speed", "Engine stalling at idle", "Idle speed too high or too low", "Rough idle especially when cold"], estimatedCostMin: 100, estimatedCostMax: 400, difficulty: "Easy" },
  { code: "P0507", title: "Idle Air Control System RPM Higher Than Expected", description: "The engine idle speed is consistently higher than what the computer expects. The engine is idling too fast and the computer cannot reduce it to the target RPM.", severity: "Low", system: "Engine", commonCauses: ["Vacuum leak", "Dirty throttle body", "Faulty IAC valve", "Air leak in intake system", "Stuck-open PCV valve"], symptoms: ["High idle speed (above normal RPM)", "Engine races when foot is off gas", "Difficulty shifting to drive/reverse", "Excessive fuel consumption at idle"], estimatedCostMin: 50, estimatedCostMax: 350, difficulty: "Easy" },
  { code: "P0520", title: "Engine Oil Pressure Sensor Circuit Malfunction", description: "The engine oil pressure sensor or its circuit is not functioning correctly. While this code relates to the sensor circuit and not necessarily actual oil pressure, low oil pressure is a serious engine-damaging condition.", severity: "High", system: "Engine", commonCauses: ["Faulty oil pressure sensor/switch", "Wiring damage to sensor", "Low engine oil level", "Oil pump wear", "Clogged oil pickup screen"], symptoms: ["Oil pressure warning light on", "Incorrect oil pressure gauge reading", "Check engine light on", "Engine noise if actual pressure is low"], estimatedCostMin: 75, estimatedCostMax: 400, difficulty: "Easy" },
  { code: "P0562", title: "System Voltage Low", description: "The engine computer has detected that the vehicle's electrical system voltage is below the minimum threshold. Normal vehicle voltage should be between 13.5 and 14.5 volts when running.", severity: "Medium", system: "Electrical", commonCauses: ["Failing alternator", "Worn alternator drive belt", "Corroded battery terminals", "Weak or dying battery", "Excessive parasitic electrical drain"], symptoms: ["Dim headlights", "Battery warning light on dash", "Electrical accessories malfunction", "Hard starting or no start"], estimatedCostMin: 100, estimatedCostMax: 600, difficulty: "Moderate" },

  // === CATALYST AND EXHAUST ===
  { code: "P0410", title: "Secondary Air Injection System Malfunction", description: "The secondary air injection (AIR) system is not working properly. This system pumps fresh air into the exhaust stream during cold starts to help the catalytic converter heat up faster and reduce cold-start emissions.", severity: "Low", system: "Emissions", commonCauses: ["Failed air pump", "Stuck check valve", "Clogged air injection passages", "Faulty air pump relay", "Cracked or disconnected air hoses"], symptoms: ["Check engine light on", "Failed emissions test", "No noticeable drivability issues", "Possible noise from air pump area"], estimatedCostMin: 200, estimatedCostMax: 700, difficulty: "Moderate" },
  { code: "P0411", title: "Secondary Air Injection System Incorrect Flow", description: "The secondary air injection system is operating but the flow is not within the expected range. Air may be flowing when it shouldn't be or not flowing enough when commanded.", severity: "Low", system: "Emissions", commonCauses: ["Carbon buildup in air passages", "Leaking check valve", "Air pump output degraded", "Blockage in air injection tubes", "Faulty air flow sensor"], symptoms: ["Check engine light on", "Failed emissions test", "Minor exhaust odor", "No significant drivability change"], estimatedCostMin: 200, estimatedCostMax: 600, difficulty: "Moderate" },

  // === VARIABLE VALVE TIMING ===
  { code: "P0010", title: "Intake Camshaft Position Actuator Circuit (Bank 1)", description: "The variable valve timing (VVT) oil control valve circuit for the intake camshaft on bank 1 has a malfunction. VVT systems optimize engine performance and efficiency by adjusting when the intake valves open and close.", severity: "Medium", system: "Engine", commonCauses: ["Faulty VVT solenoid/actuator", "Dirty engine oil restricting oil flow", "Wiring issue to the solenoid", "Clogged oil passage to actuator", "Timing chain stretch"], symptoms: ["Rough idle", "Poor fuel economy", "Decreased engine power", "Check engine light on"], estimatedCostMin: 100, estimatedCostMax: 600, difficulty: "Moderate" },
  { code: "P0011", title: "Intake Camshaft Position Timing Over-Advanced (Bank 1)", description: "The intake camshaft on bank 1 is more advanced than the computer has commanded. The VVT system is not holding the camshaft at the requested position, which can affect engine performance across the RPM range.", severity: "Medium", system: "Engine", commonCauses: ["Old or dirty engine oil", "Faulty VVT control solenoid", "Clogged oil passages", "Worn timing chain or tensioner", "Failed camshaft phaser"], symptoms: ["Rough idle", "Stalling at low RPM", "Poor fuel economy", "Engine rattle on startup"], estimatedCostMin: 150, estimatedCostMax: 1000, difficulty: "Advanced" },
  { code: "P0012", title: "Intake Camshaft Position Timing Over-Retarded (Bank 1)", description: "The intake camshaft on bank 1 is more retarded than commanded. This means the intake valves are opening and closing later than optimal, reducing engine performance especially at higher RPMs.", severity: "Medium", system: "Engine", commonCauses: ["Low oil pressure", "Dirty or incorrect oil viscosity", "Faulty VVT solenoid", "Worn timing chain", "Clogged oil screen"], symptoms: ["Loss of power at higher RPMs", "Rough idle", "Decreased fuel economy", "Possible engine noise"], estimatedCostMin: 150, estimatedCostMax: 1000, difficulty: "Advanced" },
  { code: "P0014", title: "Exhaust Camshaft Position Timing Over-Advanced (Bank 1)", description: "The exhaust camshaft on bank 1 is more advanced than commanded by the computer. This affects exhaust valve timing and can impact emission levels and engine performance.", severity: "Medium", system: "Engine", commonCauses: ["Faulty exhaust VVT solenoid", "Low or contaminated oil", "Stretched timing chain", "Worn camshaft phaser", "Restricted oil passage"], symptoms: ["Rough idle", "Loss of power", "Poor fuel economy", "Engine noise at startup"], estimatedCostMin: 150, estimatedCostMax: 1000, difficulty: "Advanced" },

  // === BODY AND MISC CODES ===
  { code: "P0600", title: "Serial Communication Link Malfunction", description: "There is a communication failure on the internal serial data bus within the engine control module. This is an internal PCM issue that affects its ability to process and communicate data.", severity: "High", system: "Electrical", commonCauses: ["PCM internal failure", "Power supply issue to PCM", "Ground circuit problem", "Wiring harness damage", "Water intrusion into PCM"], symptoms: ["Multiple warning lights on", "Engine may not start", "Erratic engine behavior", "Communication errors during diagnostics"], estimatedCostMin: 200, estimatedCostMax: 1500, difficulty: "Professional" },
  { code: "P0603", title: "Internal Control Module KAM Error", description: "The Keep Alive Memory (KAM) in the engine control module has an error. KAM stores learned values like fuel trim and idle speed that the computer has adapted over time.", severity: "Medium", system: "Electrical", commonCauses: ["Battery disconnected or replaced", "PCM power supply issue", "Corroded battery terminals", "Weak battery voltage", "Internal PCM failure"], symptoms: ["Check engine light on", "Engine may run rough temporarily", "Idle quality issues after battery disconnect", "Transmission may shift differently"], estimatedCostMin: 50, estimatedCostMax: 1000, difficulty: "Moderate" },
  { code: "P0606", title: "ECM/PCM Processor Fault", description: "The engine control module's internal processor has detected a fault within itself. This is a serious code indicating potential PCM failure that needs professional diagnosis.", severity: "Critical", system: "Electrical", commonCauses: ["Internal PCM failure", "Voltage spike or electrical surge", "Water damage to PCM", "Corroded PCM connections", "Manufacturing defect"], symptoms: ["Multiple system malfunctions", "Engine may not start", "Erratic behavior across systems", "Multiple warning lights"], estimatedCostMin: 500, estimatedCostMax: 2000, difficulty: "Professional" },

  // === ADDITIONAL HIGH-SEARCH-VOLUME CODES ===
  { code: "P0016", title: "Crankshaft/Camshaft Position Correlation (Bank 1, Sensor A)", description: "The relationship between the crankshaft position and camshaft position signals is not within the expected range. This means the engine timing components are not properly synchronized.", severity: "High", system: "Engine", commonCauses: ["Stretched or jumped timing chain", "Worn timing chain tensioner", "Faulty cam or crank sensor", "VVT system malfunction", "Incorrect timing chain installation"], symptoms: ["Rough running engine", "Rattling noise from timing area", "Loss of power", "Hard starting"], estimatedCostMin: 200, estimatedCostMax: 2000, difficulty: "Professional" },
  { code: "P0030", title: "HO2S Heater Control Circuit (Bank 1, Sensor 1)", description: "The heated oxygen sensor heater control circuit on bank 1, sensor 1 has a malfunction. The heater helps the O2 sensor reach optimal temperature faster for accurate readings.", severity: "Low", system: "Emissions", commonCauses: ["Failed O2 sensor heater", "Blown fuse", "Wiring damage", "PCM driver failure", "Corroded connector"], symptoms: ["Check engine light on", "Slightly increased emissions", "Minor fuel economy impact", "Longer warm-up enrichment"], estimatedCostMin: 100, estimatedCostMax: 350, difficulty: "Easy" },
  { code: "P0036", title: "HO2S Heater Control Circuit (Bank 1, Sensor 2)", description: "The heater circuit for the downstream oxygen sensor on bank 1 has malfunctioned. This is the post-catalytic converter sensor used to monitor converter efficiency.", severity: "Low", system: "Emissions", commonCauses: ["Failed heater element", "Blown heater fuse", "Wiring or connector issue", "PCM relay failure", "Corrosion"], symptoms: ["Check engine light on", "No drivability issues", "Higher emissions", "May fail emissions test"], estimatedCostMin: 100, estimatedCostMax: 350, difficulty: "Easy" },
  { code: "P0155", title: "O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 1)", description: "The heater element for the upstream oxygen sensor on bank 2 is not working correctly. This is the sensor before the catalytic converter on the opposite bank from cylinder 1.", severity: "Medium", system: "Emissions", commonCauses: ["Failed O2 sensor heater", "Blown fuse", "Wiring damage or short", "Corroded connector", "PCM heater driver issue"], symptoms: ["Check engine light on", "Slightly rich running when cold", "Minor fuel economy impact", "Failed emissions test"], estimatedCostMin: 100, estimatedCostMax: 400, difficulty: "Moderate" },
  { code: "P0161", title: "O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 2)", description: "The downstream oxygen sensor heater on bank 2 has failed. This is the sensor after the catalytic converter on bank 2, used to monitor converter efficiency.", severity: "Low", system: "Emissions", commonCauses: ["Burned-out heater element", "Fuse issue", "Wiring or connector fault", "PCM circuit problem", "Sensor age and wear"], symptoms: ["Check engine light on", "No performance impact", "Higher tailpipe emissions", "Emissions test failure"], estimatedCostMin: 100, estimatedCostMax: 400, difficulty: "Moderate" },
  { code: "P0341", title: "Camshaft Position Sensor Range/Performance (Bank 1)", description: "The camshaft position sensor signal on bank 1 is present but not matching expected values for the current engine conditions. This may indicate a timing issue.", severity: "High", system: "Engine", commonCauses: ["Stretched timing chain", "Worn camshaft phaser", "Faulty CMP sensor", "Tone wheel damage", "Incorrect valve timing"], symptoms: ["Poor performance", "Hard starting", "Rough idle", "Possible engine noise"], estimatedCostMin: 150, estimatedCostMax: 1200, difficulty: "Advanced" },
  { code: "P0456", title: "EVAP System Leak Detected (Very Small Leak)", description: "The evaporative emission control system has detected a very small leak during its self-diagnostic test. This is the smallest detectable leak and is often caused by aging seals or minor component wear.", severity: "Low", system: "Emissions", commonCauses: ["Gas cap seal wear", "Hairline EVAP hose crack", "Minor connector seepage", "Fuel tank pressure sensor drift", "Age-related seal degradation"], symptoms: ["Check engine light on", "No driveability issues", "No fuel smell", "May fail emissions test"], estimatedCostMin: 50, estimatedCostMax: 350, difficulty: "Moderate" },
  { code: "P2096", title: "Post Catalyst Fuel Trim System Too Lean (Bank 1)", description: "The fuel system downstream of the catalytic converter on bank 1 is reading too lean. The computer is compensating by adding fuel but the downstream O2 sensor still reads lean.", severity: "Medium", system: "Emissions", commonCauses: ["Exhaust leak before or at the catalytic converter", "Faulty downstream O2 sensor", "Catalytic converter failing", "Intake manifold leak", "Fuel system issue"], symptoms: ["Check engine light on", "Reduced fuel economy", "Possible rough idle", "Failed emissions test"], estimatedCostMin: 150, estimatedCostMax: 800, difficulty: "Moderate" },
  { code: "P2097", title: "Post Catalyst Fuel Trim System Too Rich (Bank 1)", description: "The fuel system downstream of the catalytic converter on bank 1 is reading too rich. This means too much fuel or insufficient air is present after the catalytic converter.", severity: "Medium", system: "Emissions", commonCauses: ["Catalytic converter degradation", "Faulty downstream O2 sensor", "Engine running rich upstream", "Oil or coolant entering exhaust", "Leaking fuel injector"], symptoms: ["Check engine light on", "Sulfur smell from exhaust", "Reduced performance", "Failed emissions test"], estimatedCostMin: 150, estimatedCostMax: 800, difficulty: "Moderate" },
  { code: "P2135", title: "Throttle Position Sensor Voltage Correlation", description: "The two throttle position sensor signals inside the electronic throttle body do not agree with each other. Modern vehicles use redundant TPS signals for safety, and a mismatch triggers this code.", severity: "Critical", system: "Engine", commonCauses: ["Faulty throttle body/TPS assembly", "Wiring damage to throttle body", "Corroded throttle body connector", "Carbon buildup on throttle plate", "PCM issue"], symptoms: ["Reduced engine power / limp mode", "Throttle unresponsive", "Engine may not rev above idle", "Multiple warning lights"], estimatedCostMin: 200, estimatedCostMax: 800, difficulty: "Moderate" },
  { code: "P2138", title: "Throttle Position Sensor D/E Voltage Correlation", description: "The accelerator pedal position sensors are providing conflicting signals. Like the throttle body, the accelerator pedal uses dual sensors for safety redundancy.", severity: "Critical", system: "Engine", commonCauses: ["Faulty accelerator pedal position sensor", "Wiring issue to pedal sensor", "Corroded connector", "Floor mat interfering with pedal", "PCM input circuit fault"], symptoms: ["Reduced power mode / limp mode", "Accelerator feels unresponsive", "Vehicle barely moves", "Warning lights on dashboard"], estimatedCostMin: 150, estimatedCostMax: 600, difficulty: "Moderate" },
  { code: "U0100", title: "Lost Communication with ECM/PCM", description: "Another module on the vehicle has lost communication with the engine control module over the CAN bus network. This could indicate a wiring issue, a failed module, or a network problem.", severity: "Critical", system: "Electrical", commonCauses: ["Failed ECM/PCM", "CAN bus wiring damage", "Corroded network connector", "Power supply issue to ECM", "Water damage"], symptoms: ["Multiple warning lights", "Engine may not start", "Various systems non-functional", "No communication during diagnostics"], estimatedCostMin: 200, estimatedCostMax: 2000, difficulty: "Professional" },
  { code: "U0101", title: "Lost Communication with TCM", description: "Communication has been lost between the engine computer and the transmission control module. The CAN bus network connecting these modules is interrupted.", severity: "High", system: "Transmission", commonCauses: ["Failed TCM", "CAN bus wiring fault", "Corroded connector at TCM", "Power or ground issue to TCM", "Water intrusion"], symptoms: ["Transmission stuck in limp mode", "No shifting or harsh shifts", "Multiple warning lights", "Speedometer may not work"], estimatedCostMin: 200, estimatedCostMax: 1500, difficulty: "Professional" },
  { code: "B0100", title: "Electronic Frontal Sensor 1 Malfunction", description: "The front crash sensor used by the airbag system has malfunctioned. This sensor detects frontal impacts and triggers airbag deployment.", severity: "Critical", system: "Safety", commonCauses: ["Failed crash sensor", "Wiring damage from front-end work", "Connector corrosion", "Previous collision damage", "Module communication error"], symptoms: ["Airbag warning light on", "Airbags may not deploy in a crash", "No drivability issues", "Safety system compromised"], estimatedCostMin: 200, estimatedCostMax: 800, difficulty: "Professional" },
  { code: "C0035", title: "Left Front Wheel Speed Sensor Circuit", description: "The ABS computer has detected a problem with the left front wheel speed sensor circuit. This sensor measures wheel rotation speed for the anti-lock braking and traction control systems.", severity: "Medium", system: "Safety", commonCauses: ["Failed wheel speed sensor", "Damaged sensor wiring", "Corroded connector", "Damaged tone ring", "Debris between sensor and ring"], symptoms: ["ABS warning light on", "Traction control light on", "ABS may not function", "Stability control disabled"], estimatedCostMin: 100, estimatedCostMax: 400, difficulty: "Moderate" },
  { code: "C0050", title: "Right Front Wheel Speed Sensor Circuit", description: "The right front wheel speed sensor circuit has a malfunction. Without a valid speed signal from this wheel, the ABS system cannot properly modulate braking.", severity: "Medium", system: "Safety", commonCauses: ["Wheel speed sensor failure", "Wiring damage", "Tone ring damage or rust", "Sensor gap too large", "Connector issue"], symptoms: ["ABS light on", "Traction control disabled", "Stability control light on", "Normal braking still works"], estimatedCostMin: 100, estimatedCostMax: 400, difficulty: "Moderate" },
];

// Top 10 most commonly searched codes for quick-access
export const TOP_CODES = ["P0300", "P0420", "P0171", "P0442", "P0455", "P0128", "P0401", "P0440", "P0430", "P0135"];

// Lookup by code (case-insensitive)
export function getCodeByCode(code: string): OBDCode | undefined {
  return OBD_CODES.find((c) => c.code.toLowerCase() === code.toLowerCase());
}

// Search codes by query (searches code, title, description, system, causes, symptoms)
export function searchCodes(query: string): OBDCode[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  return OBD_CODES.filter(
    (c) =>
      c.code.toLowerCase().includes(q) ||
      c.title.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.system.toLowerCase().includes(q) ||
      c.commonCauses.some((cause) => cause.toLowerCase().includes(q)) ||
      c.symptoms.some((symptom) => symptom.toLowerCase().includes(q))
  );
}

// Severity color mapping
export const SEVERITY_COLORS: Record<OBDCode["severity"], { text: string; bg: string; border: string }> = {
  Low: { text: "text-[#34d399]", bg: "bg-[rgba(52,211,153,0.1)]", border: "border-[rgba(52,211,153,0.2)]" },
  Medium: { text: "text-[#f59e0b]", bg: "bg-[rgba(245,158,11,0.1)]", border: "border-[rgba(245,158,11,0.2)]" },
  High: { text: "text-[#f97316]", bg: "bg-[rgba(249,115,22,0.1)]", border: "border-[rgba(249,115,22,0.2)]" },
  Critical: { text: "text-[#ef4444]", bg: "bg-[rgba(239,68,68,0.1)]", border: "border-[rgba(239,68,68,0.2)]" },
};

// Difficulty color mapping
export const DIFFICULTY_COLORS: Record<OBDCode["difficulty"], { text: string; bg: string }> = {
  Easy: { text: "text-[#34d399]", bg: "bg-[rgba(52,211,153,0.1)]" },
  Moderate: { text: "text-[#f59e0b]", bg: "bg-[rgba(245,158,11,0.1)]" },
  Advanced: { text: "text-[#f97316]", bg: "bg-[rgba(249,115,22,0.1)]" },
  Professional: { text: "text-[#ef4444]", bg: "bg-[rgba(239,68,68,0.1)]" },
};
